// Caesar C Code
// Generated by Caesar Compiler v1.5.1

#include "caesar/caesar_runtime.h"

// Forward declarations
int64_t num_to_str_arity1(int64_t n);

int64_t num_to_str_arity1(int64_t n) {
    int64_t r0 = n;
    int64_t r1 = 5;
    bool r2 = r0 > r1;
    if (!r2) goto else0;
    const char* r3 = "big";
    return r3;
    goto endif1;
else0:
endif1:
    const char* r4 = "small";
    return r4;
    return 0;
}

int main() {
    int64_t r5 = 10;
    int64_t r6 = num_to_str_arity1(r5);
    caesar_print_int(r6);
    int64_t r8 = 3;
    int64_t r9 = num_to_str_arity1(r8);
    caesar_print_int(r9);
    return 0;
}
