// Caesar C Code
// Generated by Caesar Compiler v1.5.1

#include "caesar/caesar_runtime.h"

// Forward declarations
int64_t str_len(const char* s);
int64_t concat_lengths(const char* a, const char* b);
int64_t is_zero(int64_t n);
int64_t is_positive(int64_t n);
int64_t is_equal(int64_t a, int64_t b);
int64_t identity_int(int64_t x);
const char* identity_str(const char* x);
double identity_float(double x);
int64_t get_first_int(int64_t a, int64_t b);
int64_t get_second_int(int64_t a, int64_t b);
const char* get_first_str(const char* a, const char* b);
const char* get_second_str(const char* a, const char* b);
int64_t both_zero(int64_t a, int64_t b);
int64_t either_zero(int64_t a, int64_t b);
int64_t add_one(int64_t n);
int64_t double_it(int64_t n);
int64_t subtract_five(int64_t n);
int64_t apply_twice(int64_t n);
int64_t compare_lens(const char* s1, const char* s2);
int64_t combine(int64_t n, const char* s);
int64_t max_of_two(int64_t a, int64_t b);
int64_t min_of_two(int64_t a, int64_t b);
int64_t in_range(int64_t n, int64_t low, int64_t high);
int64_t is_between(int64_t x, int64_t a, int64_t b);

int64_t str_len(const char* s) {
    const char* r6 = s;
    int64_t r7 = caesar_len_str(r6);
    return r7;
    return 0;
}

int64_t concat_lengths(const char* a, const char* b) {
    const char* r8 = a;
    int64_t r9 = caesar_len_str(r8);
    const char* r10 = b;
    int64_t r11 = caesar_len_str(r10);
    int64_t r12 = r9 + r11;
    return r12;
    return 0;
}

int64_t is_zero(int64_t n) {
    int64_t r25 = n;
    int64_t r26 = 0;
    bool r27 = r25 == r26;
    return r27;
    return 0;
}

int64_t is_positive(int64_t n) {
    int64_t r28 = n;
    int64_t r29 = 0;
    bool r30 = r28 > r29;
    return r30;
    return 0;
}

int64_t is_equal(int64_t a, int64_t b) {
    int64_t r31 = a;
    int64_t r32 = b;
    bool r33 = r31 == r32;
    return r33;
    return 0;
}

int64_t identity_int(int64_t x) {
    int64_t r57 = x;
    return r57;
    return 0;
}

const char* identity_str(const char* x) {
    const char* r58 = x;
    return r58;
    return 0;
}

double identity_float(double x) {
    double r59 = x;
    return r59;
    return 0;
}

int64_t get_first_int(int64_t a, int64_t b) {
    int64_t r71 = a;
    return r71;
    return 0;
}

int64_t get_second_int(int64_t a, int64_t b) {
    int64_t r72 = b;
    return r72;
    return 0;
}

const char* get_first_str(const char* a, const char* b) {
    const char* r73 = a;
    return r73;
    return 0;
}

const char* get_second_str(const char* a, const char* b) {
    const char* r74 = b;
    return r74;
    return 0;
}

int64_t both_zero(int64_t a, int64_t b) {
    int64_t r93 = a;
    int64_t r94 = 0;
    bool r95 = r93 == r94;
    int64_t r96 = b;
    int64_t r97 = 0;
    bool r98 = r96 == r97;
    bool r99 = r95 && r98;
    return r99;
    return 0;
}

int64_t either_zero(int64_t a, int64_t b) {
    int64_t r100 = a;
    int64_t r101 = 0;
    bool r102 = r100 == r101;
    int64_t r103 = b;
    int64_t r104 = 0;
    bool r105 = r103 == r104;
    bool r106 = r102 || r105;
    return r106;
    return 0;
}

int64_t add_one(int64_t n) {
    int64_t r125 = n;
    int64_t r126 = 1;
    int64_t r127 = r125 + r126;
    return r127;
    return 0;
}

int64_t double_it(int64_t n) {
    int64_t r128 = n;
    int64_t r129 = 2;
    int64_t r130 = r128 * r129;
    return r130;
    return 0;
}

int64_t subtract_five(int64_t n) {
    int64_t r131 = n;
    int64_t r132 = 5;
    int64_t r133 = r131 - r132;
    return r133;
    return 0;
}

int64_t apply_twice(int64_t n) {
    int64_t r145 = n;
    int64_t r146 = add_one(r145);
    int64_t r147 = add_one(r146);
    return r147;
    return 0;
}

int64_t compare_lens(const char* s1, const char* s2) {
    const char* r148 = s1;
    int64_t r149 = caesar_len_str(r148);
    const char* r150 = s2;
    int64_t r151 = caesar_len_str(r150);
    bool r152 = r149 == r151;
    return r152;
    return 0;
}

int64_t combine(int64_t n, const char* s) {
    int64_t r166 = n;
    const char* r167 = s;
    int64_t r168 = caesar_len_str(r167);
    int64_t r169 = r166 + r168;
    return r169;
    return 0;
}

int64_t max_of_two(int64_t a, int64_t b) {
    int64_t r180 = a;
    int64_t r181 = b;
    bool r182 = r180 > r181;
    if (!r182) goto else20;
    int64_t r183 = a;
    return r183;
    goto endif21;
else20:
endif21:
    int64_t r184 = b;
    return r184;
    return 0;
}

int64_t min_of_two(int64_t a, int64_t b) {
    int64_t r185 = a;
    int64_t r186 = b;
    bool r187 = r185 < r186;
    if (!r187) goto else23;
    int64_t r188 = a;
    return r188;
    goto endif24;
else23:
endif24:
    int64_t r189 = b;
    return r189;
    return 0;
}

int64_t in_range(int64_t n, int64_t low, int64_t high) {
    int64_t r208 = n;
    int64_t r209 = low;
    bool r210 = r208 >= r209;
    int64_t r211 = n;
    int64_t r212 = high;
    bool r213 = r211 <= r212;
    bool r214 = r210 && r213;
    return r214;
    return 0;
}

int64_t is_between(int64_t x, int64_t a, int64_t b) {
    int64_t r215 = x;
    int64_t r216 = a;
    bool r217 = r215 > r216;
    int64_t r218 = x;
    int64_t r219 = b;
    bool r220 = r218 < r219;
    bool r221 = r217 && r220;
    return r221;
    return 0;
}

int main() {
    const char* r0 = "=== GENERIC FUNCTION TYPE INFERENCE TEST ===";
    caesar_print_str(r0);
    const char* r2 = "";
    caesar_print_str(r2);
    const char* r4 = "TEST 1: len() parameter inference";
    caesar_print_str(r4);
    const char* r13 = "hello";
    int64_t r14 = str_len(r13);
    caesar_print_int(r14);
    const char* r16 = "test";
    int64_t r17 = str_len(r16);
    caesar_print_int(r17);
    const char* r19 = "hi";
    const char* r20 = "world";
    int64_t r21 = concat_lengths(r19, r20);
    caesar_print_int(r21);
    const char* r23 = "TEST 2: int comparison inference";
    caesar_print_str(r23);
    int64_t r34 = 0;
    int64_t r35 = is_zero(r34);
    caesar_print_int(r35);
    int64_t r37 = 5;
    int64_t r38 = is_zero(r37);
    caesar_print_int(r38);
    int64_t r40 = 10;
    int64_t r41 = is_positive(r40);
    caesar_print_int(r41);
    int64_t r43 = 5;
    int64_t r44 = -r43;
    int64_t r45 = is_positive(r44);
    caesar_print_int(r45);
    int64_t r47 = 5;
    int64_t r48 = 5;
    int64_t r49 = is_equal(r47, r48);
    caesar_print_int(r49);
    int64_t r51 = 3;
    int64_t r52 = 7;
    int64_t r53 = is_equal(r51, r52);
    caesar_print_int(r53);
    const char* r55 = "TEST 3: identity functions";
    caesar_print_str(r55);
    int64_t r60 = 42;
    int64_t r61 = identity_int(r60);
    caesar_print_int(r61);
    const char* r63 = "test";
    const char* r64 = identity_str(r63);
    caesar_print_str(r64);
    double r66 = 3.14;
    double r67 = identity_float(r66);
    caesar_print_double(r67);
    const char* r69 = "TEST 4: parameter selectors";
    caesar_print_str(r69);
    int64_t r75 = 10;
    int64_t r76 = 20;
    int64_t r77 = get_first_int(r75, r76);
    caesar_print_int(r77);
    int64_t r79 = 10;
    int64_t r80 = 20;
    int64_t r81 = get_second_int(r79, r80);
    caesar_print_int(r81);
    const char* r83 = "hello";
    const char* r84 = "world";
    const char* r85 = get_first_str(r83, r84);
    caesar_print_str(r85);
    const char* r87 = "hello";
    const char* r88 = "world";
    const char* r89 = get_second_str(r87, r88);
    caesar_print_str(r89);
    const char* r91 = "TEST 5: boolean with inference";
    caesar_print_str(r91);
    int64_t r107 = 0;
    int64_t r108 = 0;
    int64_t r109 = both_zero(r107, r108);
    caesar_print_int(r109);
    int64_t r111 = 0;
    int64_t r112 = 5;
    int64_t r113 = both_zero(r111, r112);
    caesar_print_int(r113);
    int64_t r115 = 0;
    int64_t r116 = 5;
    int64_t r117 = either_zero(r115, r116);
    caesar_print_int(r117);
    int64_t r119 = 3;
    int64_t r120 = 5;
    int64_t r121 = either_zero(r119, r120);
    caesar_print_int(r121);
    const char* r123 = "TEST 6: arithmetic inference";
    caesar_print_str(r123);
    int64_t r134 = 10;
    int64_t r135 = add_one(r134);
    caesar_print_int(r135);
    int64_t r137 = 7;
    int64_t r138 = double_it(r137);
    caesar_print_int(r138);
    int64_t r140 = 20;
    int64_t r141 = subtract_five(r140);
    caesar_print_int(r141);
    const char* r143 = "TEST 7: nested generic calls";
    caesar_print_str(r143);
    int64_t r153 = 5;
    int64_t r154 = apply_twice(r153);
    caesar_print_int(r154);
    const char* r156 = "hi";
    const char* r157 = "no";
    int64_t r158 = compare_lens(r156, r157);
    caesar_print_int(r158);
    const char* r160 = "hello";
    const char* r161 = "hi";
    int64_t r162 = compare_lens(r160, r161);
    caesar_print_int(r162);
    const char* r164 = "TEST 8: mixed parameters";
    caesar_print_str(r164);
    int64_t r170 = 10;
    const char* r171 = "hello";
    int64_t r172 = combine(r170, r171);
    caesar_print_int(r172);
    int64_t r174 = 5;
    const char* r175 = "test";
    int64_t r176 = combine(r174, r175);
    caesar_print_int(r176);
    const char* r178 = "TEST 9: conditional generic";
    caesar_print_str(r178);
    int64_t r190 = 10;
    int64_t r191 = 5;
    int64_t r192 = max_of_two(r190, r191);
    caesar_print_int(r192);
    int64_t r194 = 3;
    int64_t r195 = 8;
    int64_t r196 = max_of_two(r194, r195);
    caesar_print_int(r196);
    int64_t r198 = 10;
    int64_t r199 = 5;
    int64_t r200 = min_of_two(r198, r199);
    caesar_print_int(r200);
    int64_t r202 = 3;
    int64_t r203 = 8;
    int64_t r204 = min_of_two(r202, r203);
    caesar_print_int(r204);
    const char* r206 = "TEST 10: multi-comparison";
    caesar_print_str(r206);
    int64_t r222 = 5;
    int64_t r223 = 1;
    int64_t r224 = 10;
    int64_t r225 = in_range(r222, r223, r224);
    caesar_print_int(r225);
    int64_t r227 = 15;
    int64_t r228 = 1;
    int64_t r229 = 10;
    int64_t r230 = in_range(r227, r228, r229);
    caesar_print_int(r230);
    int64_t r232 = 5;
    int64_t r233 = 3;
    int64_t r234 = 7;
    int64_t r235 = is_between(r232, r233, r234);
    caesar_print_int(r235);
    int64_t r237 = 10;
    int64_t r238 = 3;
    int64_t r239 = 7;
    int64_t r240 = is_between(r237, r238, r239);
    caesar_print_int(r240);
    const char* r242 = "";
    caesar_print_str(r242);
    const char* r244 = "=== GENERIC FUNCTION TEST COMPLETE ===";
    caesar_print_str(r244);
    const char* r246 = "Successfully tested:";
    caesar_print_str(r246);
    const char* r248 = "- len() usage infers string parameters";
    caesar_print_str(r248);
    const char* r250 = "- Comparison with int literals infers int parameters";
    caesar_print_str(r250);
    const char* r252 = "- Identity functions work with multiple types";
    caesar_print_str(r252);
    const char* r254 = "- Parameter selector functions (first/second)";
    caesar_print_str(r254);
    const char* r256 = "- Boolean operations with inferred types";
    caesar_print_str(r256);
    const char* r258 = "- Arithmetic operations infer numeric types";
    caesar_print_str(r258);
    const char* r260 = "- Nested calls with generic functions";
    caesar_print_str(r260);
    const char* r262 = "- Mixed parameter types in single function";
    caesar_print_str(r262);
    const char* r264 = "- Conditionals with generic parameters";
    caesar_print_str(r264);
    const char* r266 = "- Multiple comparisons for range checking";
    caesar_print_str(r266);
    return 0;
}
