// Caesar C Code
// Generated by Caesar Compiler v1.5.1

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

// Caesar Runtime Library (inline)
typedef enum { CAESAR_INT, CAESAR_FLOAT, CAESAR_STRING, CAESAR_BOOL, CAESAR_NONE } CaesarType;
typedef struct {
    CaesarType type;
    union {
        int64_t i;
        double f;
        const char* s;
        bool b;
    } data;
} CaesarValue;

void caesar_print(int argc, CaesarValue* args) {
    for (int i = 0; i < argc; i++) {
        if (i > 0) printf(" ");
        switch (args[i].type) {
            case CAESAR_INT: printf("%lld", (long long)args[i].data.i); break;
            case CAESAR_FLOAT: printf("%g", args[i].data.f); break;
            case CAESAR_STRING: printf("%s", args[i].data.s); break;
            case CAESAR_BOOL: printf("%s", args[i].data.b ? "True" : "False"); break;
            case CAESAR_NONE: printf("None"); break;
        }
    }
    printf("\n");
}

#include <string.h>
#include <stdlib.h>
int64_t caesar_len(CaesarValue* arg) {
    switch (arg->type) {
        case CAESAR_STRING: return (int64_t)strlen(arg->data.s);
        case CAESAR_INT: return 1;  // Single value has length 1
        case CAESAR_FLOAT: return 1;
        case CAESAR_BOOL: return 1;
        case CAESAR_NONE: return 0;
        default: return 0;
    }
}

const char* caesar_str(CaesarValue* arg) {
    static char buffer[256];
    switch (arg->type) {
        case CAESAR_STRING: return arg->data.s;
        case CAESAR_INT:
            snprintf(buffer, sizeof(buffer), "%lld", (long long)arg->data.i);
            return buffer;
        case CAESAR_FLOAT:
            snprintf(buffer, sizeof(buffer), "%g", arg->data.f);
            return buffer;
        case CAESAR_BOOL:
            return arg->data.b ? "True" : "False";
        case CAESAR_NONE:
            return "None";
        default:
            return "";
    }
}

int64_t caesar_int(CaesarValue* arg) {
    switch (arg->type) {
        case CAESAR_INT: return arg->data.i;
        case CAESAR_FLOAT: return (int64_t)arg->data.f;  // Truncate float to int
        case CAESAR_BOOL: return arg->data.b ? 1 : 0;
        case CAESAR_STRING: return (int64_t)atoll(arg->data.s);  // Parse string to int
        case CAESAR_NONE: return 0;
        default: return 0;
    }
}

double caesar_float(CaesarValue* arg) {
    switch (arg->type) {
        case CAESAR_INT: return (double)arg->data.i;  // Convert int to float
        case CAESAR_FLOAT: return arg->data.f;  // Identity
        case CAESAR_BOOL: return arg->data.b ? 1.0 : 0.0;
        case CAESAR_STRING: return atof(arg->data.s);  // Parse string to float
        case CAESAR_NONE: return 0.0;
        default: return 0.0;
    }
}

#include <math.h>
double caesar_abs(CaesarValue* arg) {
    switch (arg->type) {
        case CAESAR_INT: return (double)(arg->data.i < 0 ? -arg->data.i : arg->data.i);
        case CAESAR_FLOAT: return fabs(arg->data.f);  // Use fabs for floats
        case CAESAR_BOOL: return arg->data.b ? 1.0 : 0.0;  // abs(bool) = bool as number
        case CAESAR_STRING: return fabs(atof(arg->data.s));  // Parse and abs
        case CAESAR_NONE: return 0.0;
        default: return 0.0;
    }
}

// Forward declarations
int64_t func_factorial(int64_t n);

int64_t func_factorial(int64_t n) {
    int64_t r0 = n;
    int64_t r1 = 1;
    bool r2 = r0 <= r1;
    if (!r2) goto else0;
    int64_t r3 = 1;
    return r3;
    goto endif1;
else0:
endif1:
    int64_t r4 = n;
    int64_t r5 = n;
    int64_t r6 = 1;
    int64_t r7 = r5 - r6;
    int64_t r8 = func_factorial(r7);
    int64_t r9 = r4 * r8;
    return r9;
    return 0;
    return 0;  // Safety return
}

int main() {
main_2:
    int64_t r10 = 5;
    int64_t r11 = func_factorial(r10);
    int64_t result;
    result = r11;
    int64_t r12 = result;
    {
        CaesarValue args[1];
        args[0].type = CAESAR_INT;
        args[0].data.i = r12;
        caesar_print(1, args);
    }
}
