// Caesar C Code
// Generated by Caesar Compiler v1.5.1

#include "caesar/caesar_runtime.h"

// Forward declarations
int64_t add_int(int64_t a, int64_t b);
int64_t multiply_int(int64_t x, int64_t y);
int64_t subtract_int(int64_t a, int64_t b);
int64_t greet(const char* name);
int64_t print_message(const char* msg);
int64_t welcome(const char* title, const char* firstname, const char* lastname);
double circle_area(double radius);
double circle_circumference(double radius);
double sphere_volume(double radius);
double divide(int64_t a, int64_t b);
double average_two(int64_t x, int64_t y);
double average_three(int64_t a, int64_t b, int64_t c);
int64_t add_mixed(int64_t int_val, double float_val);
int64_t multiply_mixed(int64_t int_val, double float_val);
double complex_mixed(int64_t a, int64_t b, double c);
int64_t factorial(int64_t n);
int64_t fibonacci(int64_t n);
int64_t sum_to_n(int64_t n);
int64_t power(int64_t base, int64_t exp);
int64_t caesar_auto(int64_t x);
int64_t caesar_register(int64_t x);
int64_t caesar_static(int64_t x);
int64_t caesar_volatile(int64_t x);
int64_t caesar_const(int64_t x);
int64_t caesar_double(int64_t x);
int64_t triple(int64_t x);
int64_t quadruple(int64_t x);
int64_t times_twelve(int64_t x);
int64_t increment(int64_t n);
int64_t add_two(int64_t n);
int64_t add_five(int64_t n);
int64_t add_ten(int64_t n);
int64_t abs_value(int64_t n);
int64_t max_two(int64_t a, int64_t b);
int64_t min_two(int64_t a, int64_t b);
int64_t sign(int64_t n);
double get_pi();
int64_t get_zero();
int64_t square(int64_t n);
int64_t cube(int64_t n);
int64_t negate(int64_t x);
int64_t sum_four(int64_t a, int64_t b, int64_t c, int64_t d);
int64_t product_five(int64_t a, int64_t b, int64_t c, int64_t d, int64_t e);
double weighted_average(int64_t v1, int64_t w1, int64_t v2, int64_t w2);
int64_t is_even(int64_t n);
int64_t is_positive(int64_t n);
int64_t is_in_range(int64_t n, int64_t low, int64_t high);
int64_t all_different(int64_t a, int64_t b, int64_t c);
int64_t is_even_indirect(int64_t n);
int64_t is_odd_indirect(int64_t n);
int64_t print_header();
int64_t print_footer();
int64_t print_nums(int64_t a, int64_t b);
int64_t sum_range(int64_t n);
int64_t test_eq(int64_t a, int64_t b);
int64_t test_ne(int64_t a, int64_t b);
int64_t test_lt(int64_t a, int64_t b);
int64_t test_le(int64_t a, int64_t b);
int64_t test_gt(int64_t a, int64_t b);
int64_t test_ge(int64_t a, int64_t b);
int64_t test_add(int64_t a, int64_t b);
int64_t test_sub(int64_t a, int64_t b);
int64_t test_mul(int64_t a, int64_t b);
double test_div(int64_t a, int64_t b);
int64_t test_mod(int64_t a, int64_t b);
int64_t test_neg(int64_t a);
int64_t print_three_strings(const char* s1, const char* s2, const char* s3);
int64_t print_labeled(const char* label, const char* value);
int64_t early_return_test(int64_t n);

int64_t add_int(int64_t a, int64_t b) {
    int64_t r4 = a;
    int64_t r5 = b;
    int64_t r6 = r4 + r5;
    return r6;
    return 0;
}

int64_t multiply_int(int64_t x, int64_t y) {
    int64_t r7 = x;
    int64_t r8 = y;
    int64_t r9 = r7 * r8;
    return r9;
    return 0;
}

int64_t subtract_int(int64_t a, int64_t b) {
    int64_t r10 = a;
    int64_t r11 = b;
    int64_t r12 = r10 - r11;
    return r12;
    return 0;
}

int64_t greet(const char* name) {
    const char* r27 = "Hello";
    caesar_print_str(r27);
    const char* r29 = name;
    caesar_print_str(r29);
    return 0;
}

int64_t print_message(const char* msg) {
    const char* r31 = msg;
    caesar_print_str(r31);
    return 0;
}

int64_t welcome(const char* title, const char* firstname, const char* lastname) {
    const char* r33 = title;
    caesar_print_str(r33);
    const char* r35 = firstname;
    caesar_print_str(r35);
    const char* r37 = lastname;
    caesar_print_str(r37);
    return 0;
}

double circle_area(double radius) {
    double pi = 0;

    double r49 = 3.14159;
    pi = r49;
    double r50 = pi;
    double r51 = radius;
    double r52 = r50 * r51;
    double r53 = radius;
    double r54 = r52 * r53;
    return r54;
    return 0;
}

double circle_circumference(double radius) {
    double pi = 0;

    double r55 = 3.14159;
    pi = r55;
    int64_t r56 = 2;
    double r57 = pi;
    double r58 = r56 * r57;
    double r59 = radius;
    double r60 = r58 * r59;
    return r60;
    return 0;
}

double sphere_volume(double radius) {
    double pi = 0;

    double r61 = 3.14159;
    pi = r61;
    int64_t r62 = 4;
    double r63 = pi;
    double r64 = r62 * r63;
    double r65 = radius;
    double r66 = r64 * r65;
    double r67 = radius;
    double r68 = r66 * r67;
    double r69 = radius;
    double r70 = r68 * r69;
    int64_t r71 = 3;
    double r72 = r70 / (double)r71;
    return r72;
    return 0;
}

double divide(int64_t a, int64_t b) {
    int64_t r84 = a;
    int64_t r85 = b;
    double r86 = (double)r84 / (double)r85;
    return r86;
    return 0;
}

double average_two(int64_t x, int64_t y) {
    int64_t r87 = x;
    int64_t r88 = y;
    int64_t r89 = r87 + r88;
    int64_t r90 = 2;
    double r91 = (double)r89 / (double)r90;
    return r91;
    return 0;
}

double average_three(int64_t a, int64_t b, int64_t c) {
    int64_t r92 = a;
    int64_t r93 = b;
    int64_t r94 = r92 + r93;
    int64_t r95 = c;
    int64_t r96 = r94 + r95;
    int64_t r97 = 3;
    double r98 = (double)r96 / (double)r97;
    return r98;
    return 0;
}

int64_t add_mixed(int64_t int_val, double float_val) {
    int64_t r126 = int_val;
    double r127 = float_val;
    double r128 = r126 + r127;
    return r128;
    return 0;
}

int64_t multiply_mixed(int64_t int_val, double float_val) {
    int64_t r129 = int_val;
    double r130 = float_val;
    double r131 = r129 * r130;
    return r131;
    return 0;
}

double complex_mixed(int64_t a, int64_t b, double c) {
    double result3 = 0;
    int64_t result2 = 0;
    int64_t result1 = 0;

    int64_t r132 = a;
    int64_t r133 = b;
    int64_t r134 = r132 + r133;
    result1 = r134;
    int64_t r135 = result1;
    double r136 = c;
    double r137 = r135 * r136;
    result2 = r137;
    double r138 = result2;
    int64_t r139 = 2;
    double r140 = r138 / (double)r139;
    result3 = r140;
    double r141 = result3;
    return r141;
    return 0;
}

int64_t factorial(int64_t n) {
    int64_t r157 = n;
    int64_t r158 = 1;
    bool r159 = r157 <= r158;
    if (!r159) goto else15;
    int64_t r160 = 1;
    return r160;
    goto endif16;
else15:
endif16:
    int64_t r161 = n;
    int64_t r162 = n;
    int64_t r163 = 1;
    int64_t r164 = r162 - r163;
    int64_t r165 = factorial(r164);
    int64_t r166 = r161 * r165;
    return r166;
    return 0;
}

int64_t fibonacci(int64_t n) {
    int64_t r167 = n;
    int64_t r168 = 1;
    bool r169 = r167 <= r168;
    if (!r169) goto else18;
    int64_t r170 = n;
    return r170;
    goto endif19;
else18:
endif19:
    int64_t r171 = n;
    int64_t r172 = 1;
    int64_t r173 = r171 - r172;
    int64_t r174 = fibonacci(r173);
    int64_t r175 = n;
    int64_t r176 = 2;
    int64_t r177 = r175 - r176;
    int64_t r178 = fibonacci(r177);
    int64_t r179 = r174 + r178;
    return r179;
    return 0;
}

int64_t sum_to_n(int64_t n) {
    int64_t r180 = n;
    int64_t r181 = 0;
    bool r182 = r180 <= r181;
    if (!r182) goto else21;
    int64_t r183 = 0;
    return r183;
    goto endif22;
else21:
endif22:
    int64_t r184 = n;
    int64_t r185 = n;
    int64_t r186 = 1;
    int64_t r187 = r185 - r186;
    int64_t r188 = sum_to_n(r187);
    int64_t r189 = r184 + r188;
    return r189;
    return 0;
}

int64_t power(int64_t base, int64_t exp) {
    int64_t r190 = exp;
    int64_t r191 = 0;
    bool r192 = r190 == r191;
    if (!r192) goto else24;
    int64_t r193 = 1;
    return r193;
    goto endif25;
else24:
endif25:
    int64_t r194 = exp;
    int64_t r195 = 1;
    bool r196 = r194 == r195;
    if (!r196) goto else26;
    int64_t r197 = base;
    return r197;
    goto endif27;
else26:
endif27:
    int64_t r198 = base;
    int64_t r199 = base;
    int64_t r200 = exp;
    int64_t r201 = 1;
    int64_t r202 = r200 - r201;
    int64_t r203 = power(r199, r202);
    int64_t r204 = r198 * r203;
    return r204;
    return 0;
}

int64_t caesar_auto(int64_t x) {
    int64_t r233 = x;
    int64_t r234 = 1;
    int64_t r235 = r233 + r234;
    return r235;
    return 0;
}

int64_t caesar_register(int64_t x) {
    int64_t r236 = x;
    int64_t r237 = 1;
    int64_t r238 = r236 - r237;
    return r238;
    return 0;
}

int64_t caesar_static(int64_t x) {
    int64_t r239 = x;
    int64_t r240 = 2;
    int64_t r241 = r239 * r240;
    return r241;
    return 0;
}

int64_t caesar_volatile(int64_t x) {
    int64_t r242 = x;
    int64_t r243 = 3;
    int64_t r244 = r242 * r243;
    return r244;
    return 0;
}

int64_t caesar_const(int64_t x) {
    int64_t r245 = x;
    int64_t r246 = 10;
    int64_t r247 = r245 + r246;
    return r247;
    return 0;
}

int64_t caesar_double(int64_t x) {
    int64_t r265 = x;
    int64_t r266 = x;
    int64_t r267 = r265 + r266;
    return r267;
    return 0;
}

int64_t triple(int64_t x) {
    int64_t r268 = x;
    int64_t r269 = x;
    int64_t r270 = r268 + r269;
    int64_t r271 = x;
    int64_t r272 = r270 + r271;
    return r272;
    return 0;
}

int64_t quadruple(int64_t x) {
    int64_t r273 = x;
    int64_t r274 = caesar_double(r273);
    int64_t r275 = caesar_double(r274);
    return r275;
    return 0;
}

int64_t times_twelve(int64_t x) {
    int64_t r276 = x;
    int64_t r277 = quadruple(r276);
    int64_t r278 = triple(r277);
    return r278;
    return 0;
}

int64_t increment(int64_t n) {
    int64_t r293 = n;
    int64_t r294 = 1;
    int64_t r295 = r293 + r294;
    return r295;
    return 0;
}

int64_t add_two(int64_t n) {
    int64_t r296 = n;
    int64_t r297 = increment(r296);
    int64_t r298 = increment(r297);
    return r298;
    return 0;
}

int64_t add_five(int64_t n) {
    int64_t r299 = n;
    int64_t r300 = increment(r299);
    int64_t r301 = add_two(r300);
    int64_t r302 = add_two(r301);
    return r302;
    return 0;
}

int64_t add_ten(int64_t n) {
    int64_t r303 = n;
    int64_t r304 = add_five(r303);
    int64_t r305 = add_five(r304);
    return r305;
    return 0;
}

int64_t abs_value(int64_t n) {
    int64_t r320 = n;
    int64_t r321 = 0;
    bool r322 = r320 < r321;
    if (!r322) goto else42;
    int64_t r323 = n;
    int64_t r324 = -r323;
    return r324;
    goto endif43;
else42:
endif43:
    int64_t r325 = n;
    return r325;
    return 0;
}

int64_t max_two(int64_t a, int64_t b) {
    int64_t r326 = a;
    int64_t r327 = b;
    bool r328 = r326 > r327;
    if (!r328) goto else45;
    int64_t r329 = a;
    return r329;
    goto endif46;
else45:
endif46:
    int64_t r330 = b;
    return r330;
    return 0;
}

int64_t min_two(int64_t a, int64_t b) {
    int64_t r331 = a;
    int64_t r332 = b;
    bool r333 = r331 < r332;
    if (!r333) goto else48;
    int64_t r334 = a;
    return r334;
    goto endif49;
else48:
endif49:
    int64_t r335 = b;
    return r335;
    return 0;
}

int64_t sign(int64_t n) {
    int64_t r336 = n;
    int64_t r337 = 0;
    bool r338 = r336 < r337;
    if (!r338) goto else51;
    int64_t r339 = 1;
    int64_t r340 = -r339;
    return r340;
    goto endif52;
else51:
endif52:
    int64_t r341 = n;
    int64_t r342 = 0;
    bool r343 = r341 > r342;
    if (!r343) goto else53;
    int64_t r344 = 1;
    return r344;
    goto endif54;
else53:
endif54:
    int64_t r345 = 0;
    return r345;
    return 0;
}

double get_pi() {
    double r381 = 3.14159;
    return r381;
    return 0;
}

int64_t get_zero() {
    int64_t r382 = 0;
    return r382;
    return 0;
}

int64_t square(int64_t n) {
    int64_t r383 = n;
    int64_t r384 = n;
    int64_t r385 = r383 * r384;
    return r385;
    return 0;
}

int64_t cube(int64_t n) {
    int64_t r386 = n;
    int64_t r387 = n;
    int64_t r388 = r386 * r387;
    int64_t r389 = n;
    int64_t r390 = r388 * r389;
    return r390;
    return 0;
}

int64_t negate(int64_t x) {
    int64_t r391 = x;
    int64_t r392 = -r391;
    return r392;
    return 0;
}

int64_t sum_four(int64_t a, int64_t b, int64_t c, int64_t d) {
    int64_t r418 = a;
    int64_t r419 = b;
    int64_t r420 = r418 + r419;
    int64_t r421 = c;
    int64_t r422 = r420 + r421;
    int64_t r423 = d;
    int64_t r424 = r422 + r423;
    return r424;
    return 0;
}

int64_t product_five(int64_t a, int64_t b, int64_t c, int64_t d, int64_t e) {
    int64_t r425 = a;
    int64_t r426 = b;
    int64_t r427 = r425 * r426;
    int64_t r428 = c;
    int64_t r429 = r427 * r428;
    int64_t r430 = d;
    int64_t r431 = r429 * r430;
    int64_t r432 = e;
    int64_t r433 = r431 * r432;
    return r433;
    return 0;
}

double weighted_average(int64_t v1, int64_t w1, int64_t v2, int64_t w2) {
    int64_t r434 = v1;
    int64_t r435 = w1;
    int64_t r436 = r434 * r435;
    int64_t r437 = v2;
    int64_t r438 = w2;
    int64_t r439 = r437 * r438;
    int64_t r440 = r436 + r439;
    int64_t r441 = w1;
    int64_t r442 = w2;
    int64_t r443 = r441 + r442;
    double r444 = (double)r440 / (double)r443;
    return r444;
    return 0;
}

int64_t is_even(int64_t n) {
    int64_t r472 = n;
    int64_t r473 = 2;
    int64_t r474 = r472 % r473;
    int64_t r475 = 0;
    bool r476 = r474 == r475;
    if (!r476) goto else64;
    int64_t r477 = 1;
    return r477;
    goto endif65;
else64:
endif65:
    int64_t r478 = 0;
    return r478;
    return 0;
}

int64_t is_positive(int64_t n) {
    int64_t r479 = n;
    int64_t r480 = 0;
    bool r481 = r479 > r480;
    if (!r481) goto else67;
    int64_t r482 = 1;
    return r482;
    goto endif68;
else67:
endif68:
    int64_t r483 = 0;
    return r483;
    return 0;
}

int64_t is_in_range(int64_t n, int64_t low, int64_t high) {
    int64_t r484 = n;
    int64_t r485 = low;
    bool r486 = r484 >= r485;
    if (!r486) goto else70;
    int64_t r487 = n;
    int64_t r488 = high;
    bool r489 = r487 <= r488;
    if (!r489) goto else72;
    int64_t r490 = 1;
    return r490;
    goto endif73;
else72:
endif73:
    goto endif71;
else70:
endif71:
    int64_t r491 = 0;
    return r491;
    return 0;
}

int64_t all_different(int64_t a, int64_t b, int64_t c) {
    int64_t r492 = a;
    int64_t r493 = b;
    bool r494 = r492 != r493;
    if (!r494) goto else75;
    int64_t r495 = b;
    int64_t r496 = c;
    bool r497 = r495 != r496;
    if (!r497) goto else77;
    int64_t r498 = a;
    int64_t r499 = c;
    bool r500 = r498 != r499;
    if (!r500) goto else79;
    int64_t r501 = 1;
    return r501;
    goto endif80;
else79:
endif80:
    goto endif78;
else77:
endif78:
    goto endif76;
else75:
endif76:
    int64_t r502 = 0;
    return r502;
    return 0;
}

int64_t is_even_indirect(int64_t n) {
    int64_t r538 = n;
    int64_t r539 = 0;
    bool r540 = r538 == r539;
    if (!r540) goto else82;
    int64_t r541 = 1;
    return r541;
    goto endif83;
else82:
endif83:
    int64_t r542 = n;
    int64_t r543 = 1;
    int64_t r544 = r542 - r543;
    int64_t r545 = is_odd_indirect(r544);
    return r545;
    return 0;
}

int64_t is_odd_indirect(int64_t n) {
    int64_t r546 = n;
    int64_t r547 = 0;
    bool r548 = r546 == r547;
    if (!r548) goto else85;
    int64_t r549 = 0;
    return r549;
    goto endif86;
else85:
endif86:
    int64_t r550 = n;
    int64_t r551 = 1;
    int64_t r552 = r550 - r551;
    int64_t r553 = is_even_indirect(r552);
    return r553;
    return 0;
}

int64_t print_header() {
    const char* r574 = "=== HEADER ===";
    caesar_print_str(r574);
    return 0;
}

int64_t print_footer() {
    const char* r576 = "=== FOOTER ===";
    caesar_print_str(r576);
    return 0;
}

int64_t print_nums(int64_t a, int64_t b) {
    int64_t r578 = a;
    caesar_print_int(r578);
    int64_t r580 = b;
    caesar_print_int(r580);
    return 0;
}

int64_t sum_range(int64_t n) {
    int64_t r589 = n;
    int64_t r590 = 0;
    bool r591 = r589 <= r590;
    if (!r591) goto else91;
    int64_t r592 = 0;
    return r592;
    goto endif92;
else91:
endif92:
    int64_t r593 = n;
    int64_t r594 = n;
    int64_t r595 = 1;
    int64_t r596 = r594 - r595;
    int64_t r597 = sum_range(r596);
    int64_t r598 = r593 + r597;
    return r598;
    return 0;
}

int64_t test_eq(int64_t a, int64_t b) {
    int64_t r607 = a;
    int64_t r608 = b;
    bool r609 = r607 == r608;
    if (!r609) goto else94;
    int64_t r610 = 1;
    return r610;
    goto endif95;
else94:
endif95:
    int64_t r611 = 0;
    return r611;
    return 0;
}

int64_t test_ne(int64_t a, int64_t b) {
    int64_t r612 = a;
    int64_t r613 = b;
    bool r614 = r612 != r613;
    if (!r614) goto else97;
    int64_t r615 = 1;
    return r615;
    goto endif98;
else97:
endif98:
    int64_t r616 = 0;
    return r616;
    return 0;
}

int64_t test_lt(int64_t a, int64_t b) {
    int64_t r617 = a;
    int64_t r618 = b;
    bool r619 = r617 < r618;
    if (!r619) goto else100;
    int64_t r620 = 1;
    return r620;
    goto endif101;
else100:
endif101:
    int64_t r621 = 0;
    return r621;
    return 0;
}

int64_t test_le(int64_t a, int64_t b) {
    int64_t r622 = a;
    int64_t r623 = b;
    bool r624 = r622 <= r623;
    if (!r624) goto else103;
    int64_t r625 = 1;
    return r625;
    goto endif104;
else103:
endif104:
    int64_t r626 = 0;
    return r626;
    return 0;
}

int64_t test_gt(int64_t a, int64_t b) {
    int64_t r627 = a;
    int64_t r628 = b;
    bool r629 = r627 > r628;
    if (!r629) goto else106;
    int64_t r630 = 1;
    return r630;
    goto endif107;
else106:
endif107:
    int64_t r631 = 0;
    return r631;
    return 0;
}

int64_t test_ge(int64_t a, int64_t b) {
    int64_t r632 = a;
    int64_t r633 = b;
    bool r634 = r632 >= r633;
    if (!r634) goto else109;
    int64_t r635 = 1;
    return r635;
    goto endif110;
else109:
endif110:
    int64_t r636 = 0;
    return r636;
    return 0;
}

int64_t test_add(int64_t a, int64_t b) {
    int64_t r687 = a;
    int64_t r688 = b;
    int64_t r689 = r687 + r688;
    return r689;
    return 0;
}

int64_t test_sub(int64_t a, int64_t b) {
    int64_t r690 = a;
    int64_t r691 = b;
    int64_t r692 = r690 - r691;
    return r692;
    return 0;
}

int64_t test_mul(int64_t a, int64_t b) {
    int64_t r693 = a;
    int64_t r694 = b;
    int64_t r695 = r693 * r694;
    return r695;
    return 0;
}

double test_div(int64_t a, int64_t b) {
    int64_t r696 = a;
    int64_t r697 = b;
    double r698 = (double)r696 / (double)r697;
    return r698;
    return 0;
}

int64_t test_mod(int64_t a, int64_t b) {
    int64_t r699 = a;
    int64_t r700 = b;
    int64_t r701 = r699 % r700;
    return r701;
    return 0;
}

int64_t test_neg(int64_t a) {
    int64_t r702 = a;
    int64_t r703 = -r702;
    return r703;
    return 0;
}

int64_t print_three_strings(const char* s1, const char* s2, const char* s3) {
    const char* r757 = s1;
    caesar_print_str(r757);
    const char* r759 = s2;
    caesar_print_str(r759);
    const char* r761 = s3;
    caesar_print_str(r761);
    return 0;
}

int64_t print_labeled(const char* label, const char* value) {
    const char* r763 = label;
    caesar_print_str(r763);
    const char* r765 = value;
    caesar_print_str(r765);
    return 0;
}

int64_t early_return_test(int64_t n) {
    int64_t r779 = n;
    int64_t r780 = 0;
    bool r781 = r779 < r780;
    if (!r781) goto else120;
    int64_t r782 = 999;
    int64_t r783 = -r782;
    return r783;
    goto endif121;
else120:
endif121:
    int64_t r784 = n;
    int64_t r785 = 0;
    bool r786 = r784 == r785;
    if (!r786) goto else122;
    int64_t r787 = 0;
    return r787;
    goto endif123;
else122:
endif123:
    int64_t r788 = n;
    int64_t r789 = 1;
    bool r790 = r788 == r789;
    if (!r790) goto else124;
    int64_t r791 = 100;
    return r791;
    goto endif125;
else124:
endif125:
    int64_t r792 = n;
    int64_t r793 = 2;
    bool r794 = r792 == r793;
    if (!r794) goto else126;
    int64_t r795 = 200;
    return r795;
    goto endif127;
else126:
endif127:
    int64_t r796 = 999;
    return r796;
    return 0;
}

int main() {
    // User variables
    double pi = 0;
    double result3 = 0;
    double result2 = 0;
    int64_t result1 = 0;

    const char* r0 = "=== COMPREHENSIVE TEST SUITE START ===";
    caesar_print_str(r0);
    const char* r2 = "TEST 1: Integer Functions";
    caesar_print_str(r2);
    int64_t r13 = 5;
    int64_t r14 = 3;
    int64_t r15 = add_int(r13, r14);
    caesar_print_int(r15);
    int64_t r17 = 4;
    int64_t r18 = 7;
    int64_t r19 = multiply_int(r17, r18);
    caesar_print_int(r19);
    int64_t r21 = 10;
    int64_t r22 = 3;
    int64_t r23 = subtract_int(r21, r22);
    caesar_print_int(r23);
    const char* r25 = "TEST 2: String Parameters";
    caesar_print_str(r25);
    const char* r39 = "Alice";
    int64_t r40 = greet(r39);
    const char* r41 = "Test Message";
    int64_t r42 = print_message(r41);
    const char* r43 = "Dr.";
    const char* r44 = "John";
    const char* r45 = "Smith";
    int64_t r46 = welcome(r43, r44, r45);
    const char* r47 = "TEST 3: Float Literals and Arithmetic";
    caesar_print_str(r47);
    double r73 = 5.0;
    int64_t r74 = circle_area(r73);
    caesar_print_int(r74);
    double r76 = 10.0;
    int64_t r77 = circle_circumference(r76);
    caesar_print_int(r77);
    double r79 = 3.0;
    int64_t r80 = sphere_volume(r79);
    caesar_print_int(r80);
    const char* r82 = "TEST 4: True Division";
    caesar_print_str(r82);
    int64_t r99 = 10;
    int64_t r100 = 3;
    int64_t r101 = divide(r99, r100);
    caesar_print_int(r101);
    int64_t r103 = 100;
    int64_t r104 = 7;
    int64_t r105 = divide(r103, r104);
    caesar_print_int(r105);
    int64_t r107 = 22;
    int64_t r108 = 7;
    int64_t r109 = divide(r107, r108);
    caesar_print_int(r109);
    int64_t r111 = 10;
    int64_t r112 = 20;
    int64_t r113 = average_two(r111, r112);
    caesar_print_int(r113);
    int64_t r115 = 5;
    int64_t r116 = 8;
    int64_t r117 = average_two(r115, r116);
    caesar_print_int(r117);
    int64_t r119 = 5;
    int64_t r120 = 10;
    int64_t r121 = 15;
    int64_t r122 = average_three(r119, r120, r121);
    caesar_print_int(r122);
    const char* r124 = "TEST 5: Mixed Type Arithmetic";
    caesar_print_str(r124);
    int64_t r142 = 10;
    double r143 = 2.5;
    int64_t r144 = add_mixed(r142, r143);
    caesar_print_int(r144);
    int64_t r146 = 8;
    double r147 = 1.5;
    int64_t r148 = multiply_mixed(r146, r147);
    caesar_print_int(r148);
    int64_t r150 = 5;
    int64_t r151 = 3;
    double r152 = 2.0;
    int64_t r153 = complex_mixed(r150, r151, r152);
    caesar_print_int(r153);
    const char* r155 = "TEST 6: Recursive Functions";
    caesar_print_str(r155);
    int64_t r205 = 5;
    int64_t r206 = factorial(r205);
    caesar_print_int(r206);
    int64_t r208 = 6;
    int64_t r209 = factorial(r208);
    caesar_print_int(r209);
    int64_t r211 = 7;
    int64_t r212 = fibonacci(r211);
    caesar_print_int(r212);
    int64_t r214 = 8;
    int64_t r215 = fibonacci(r214);
    caesar_print_int(r215);
    int64_t r217 = 10;
    int64_t r218 = sum_to_n(r217);
    caesar_print_int(r218);
    int64_t r220 = 20;
    int64_t r221 = sum_to_n(r220);
    caesar_print_int(r221);
    int64_t r223 = 2;
    int64_t r224 = 5;
    int64_t r225 = power(r223, r224);
    caesar_print_int(r225);
    int64_t r227 = 3;
    int64_t r228 = 4;
    int64_t r229 = power(r227, r228);
    caesar_print_int(r229);
    const char* r231 = "TEST 7: C Reserved Keywords";
    caesar_print_str(r231);
    int64_t r248 = 10;
    int64_t r249 = caesar_auto(r248);
    caesar_print_int(r249);
    int64_t r251 = 10;
    int64_t r252 = caesar_register(r251);
    caesar_print_int(r252);
    int64_t r254 = 5;
    int64_t r255 = caesar_static(r254);
    caesar_print_int(r255);
    int64_t r257 = 7;
    int64_t r258 = caesar_volatile(r257);
    caesar_print_int(r258);
    int64_t r260 = 5;
    int64_t r261 = caesar_const(r260);
    caesar_print_int(r261);
    const char* r263 = "TEST 8: Nested Function Calls";
    caesar_print_str(r263);
    int64_t r279 = 7;
    int64_t r280 = caesar_double(r279);
    caesar_print_int(r280);
    int64_t r282 = 5;
    int64_t r283 = triple(r282);
    caesar_print_int(r283);
    int64_t r285 = 4;
    int64_t r286 = quadruple(r285);
    caesar_print_int(r286);
    int64_t r288 = 2;
    int64_t r289 = times_twelve(r288);
    caesar_print_int(r289);
    const char* r291 = "TEST 9: Chained Function Calls";
    caesar_print_str(r291);
    int64_t r306 = 10;
    int64_t r307 = increment(r306);
    caesar_print_int(r307);
    int64_t r309 = 10;
    int64_t r310 = add_two(r309);
    caesar_print_int(r310);
    int64_t r312 = 10;
    int64_t r313 = add_five(r312);
    caesar_print_int(r313);
    int64_t r315 = 10;
    int64_t r316 = add_ten(r315);
    caesar_print_int(r316);
    const char* r318 = "TEST 10: Multiple Return Paths";
    caesar_print_str(r318);
    int64_t r346 = 15;
    int64_t r347 = -r346;
    int64_t r348 = abs_value(r347);
    caesar_print_int(r348);
    int64_t r350 = 20;
    int64_t r351 = abs_value(r350);
    caesar_print_int(r351);
    int64_t r353 = 7;
    int64_t r354 = 12;
    int64_t r355 = max_two(r353, r354);
    caesar_print_int(r355);
    int64_t r357 = 25;
    int64_t r358 = 10;
    int64_t r359 = max_two(r357, r358);
    caesar_print_int(r359);
    int64_t r361 = 7;
    int64_t r362 = 12;
    int64_t r363 = min_two(r361, r362);
    caesar_print_int(r363);
    int64_t r365 = 25;
    int64_t r366 = 10;
    int64_t r367 = min_two(r365, r366);
    caesar_print_int(r367);
    int64_t r369 = 5;
    int64_t r370 = -r369;
    int64_t r371 = sign(r370);
    caesar_print_int(r371);
    int64_t r373 = 10;
    int64_t r374 = sign(r373);
    caesar_print_int(r374);
    int64_t r376 = 0;
    int64_t r377 = sign(r376);
    caesar_print_int(r377);
    const char* r379 = "TEST 11: Zero and Single Parameter Functions";
    caesar_print_str(r379);
    int64_t r393 = get_pi();
    caesar_print_int(r393);
    int64_t r395 = get_zero();
    caesar_print_int(r395);
    int64_t r397 = 5;
    int64_t r398 = square(r397);
    caesar_print_int(r398);
    int64_t r400 = 7;
    int64_t r401 = square(r400);
    caesar_print_int(r401);
    int64_t r403 = 3;
    int64_t r404 = cube(r403);
    caesar_print_int(r404);
    int64_t r406 = 4;
    int64_t r407 = cube(r406);
    caesar_print_int(r407);
    int64_t r409 = 10;
    int64_t r410 = negate(r409);
    caesar_print_int(r410);
    int64_t r412 = 5;
    int64_t r413 = -r412;
    int64_t r414 = negate(r413);
    caesar_print_int(r414);
    const char* r416 = "TEST 12: Many Parameters";
    caesar_print_str(r416);
    int64_t r445 = 1;
    int64_t r446 = 2;
    int64_t r447 = 3;
    int64_t r448 = 4;
    int64_t r449 = sum_four(r445, r446, r447, r448);
    caesar_print_int(r449);
    int64_t r451 = 5;
    int64_t r452 = 10;
    int64_t r453 = 15;
    int64_t r454 = 20;
    int64_t r455 = sum_four(r451, r452, r453, r454);
    caesar_print_int(r455);
    int64_t r457 = 1;
    int64_t r458 = 2;
    int64_t r459 = 3;
    int64_t r460 = 4;
    int64_t r461 = 5;
    int64_t r462 = product_five(r457, r458, r459, r460, r461);
    caesar_print_int(r462);
    int64_t r464 = 10;
    int64_t r465 = 3;
    int64_t r466 = 20;
    int64_t r467 = 7;
    int64_t r468 = weighted_average(r464, r465, r466, r467);
    caesar_print_int(r468);
    const char* r470 = "TEST 13: Complex Logic";
    caesar_print_str(r470);
    int64_t r503 = 4;
    int64_t r504 = is_even(r503);
    caesar_print_int(r504);
    int64_t r506 = 7;
    int64_t r507 = is_even(r506);
    caesar_print_int(r507);
    int64_t r509 = 10;
    int64_t r510 = is_positive(r509);
    caesar_print_int(r510);
    int64_t r512 = 5;
    int64_t r513 = -r512;
    int64_t r514 = is_positive(r513);
    caesar_print_int(r514);
    int64_t r516 = 5;
    int64_t r517 = 1;
    int64_t r518 = 10;
    int64_t r519 = is_in_range(r516, r517, r518);
    caesar_print_int(r519);
    int64_t r521 = 15;
    int64_t r522 = 1;
    int64_t r523 = 10;
    int64_t r524 = is_in_range(r521, r522, r523);
    caesar_print_int(r524);
    int64_t r526 = 1;
    int64_t r527 = 2;
    int64_t r528 = 3;
    int64_t r529 = all_different(r526, r527, r528);
    caesar_print_int(r529);
    int64_t r531 = 1;
    int64_t r532 = 1;
    int64_t r533 = 3;
    int64_t r534 = all_different(r531, r532, r533);
    caesar_print_int(r534);
    const char* r536 = "TEST 14: Mutual Recursion";
    caesar_print_str(r536);
    int64_t r554 = 0;
    int64_t r555 = is_even_indirect(r554);
    caesar_print_int(r555);
    int64_t r557 = 4;
    int64_t r558 = is_even_indirect(r557);
    caesar_print_int(r558);
    int64_t r560 = 7;
    int64_t r561 = is_even_indirect(r560);
    caesar_print_int(r561);
    int64_t r563 = 0;
    int64_t r564 = is_odd_indirect(r563);
    caesar_print_int(r564);
    int64_t r566 = 3;
    int64_t r567 = is_odd_indirect(r566);
    caesar_print_int(r567);
    int64_t r569 = 6;
    int64_t r570 = is_odd_indirect(r569);
    caesar_print_int(r570);
    const char* r572 = "TEST 15: Void Functions";
    caesar_print_str(r572);
    int64_t r582 = print_header();
    int64_t r583 = print_footer();
    int64_t r584 = 42;
    int64_t r585 = 99;
    int64_t r586 = print_nums(r584, r585);
    const char* r587 = "TEST 16: Deep Recursion";
    caesar_print_str(r587);
    int64_t r599 = 50;
    int64_t r600 = sum_range(r599);
    caesar_print_int(r600);
    int64_t r602 = 100;
    int64_t r603 = sum_range(r602);
    caesar_print_int(r603);
    const char* r605 = "TEST 17: All Comparison Operators";
    caesar_print_str(r605);
    int64_t r637 = 5;
    int64_t r638 = 5;
    int64_t r639 = test_eq(r637, r638);
    caesar_print_int(r639);
    int64_t r641 = 5;
    int64_t r642 = 7;
    int64_t r643 = test_eq(r641, r642);
    caesar_print_int(r643);
    int64_t r645 = 5;
    int64_t r646 = 7;
    int64_t r647 = test_ne(r645, r646);
    caesar_print_int(r647);
    int64_t r649 = 5;
    int64_t r650 = 5;
    int64_t r651 = test_ne(r649, r650);
    caesar_print_int(r651);
    int64_t r653 = 3;
    int64_t r654 = 7;
    int64_t r655 = test_lt(r653, r654);
    caesar_print_int(r655);
    int64_t r657 = 7;
    int64_t r658 = 3;
    int64_t r659 = test_lt(r657, r658);
    caesar_print_int(r659);
    int64_t r661 = 5;
    int64_t r662 = 5;
    int64_t r663 = test_le(r661, r662);
    caesar_print_int(r663);
    int64_t r665 = 7;
    int64_t r666 = 3;
    int64_t r667 = test_le(r665, r666);
    caesar_print_int(r667);
    int64_t r669 = 7;
    int64_t r670 = 3;
    int64_t r671 = test_gt(r669, r670);
    caesar_print_int(r671);
    int64_t r673 = 3;
    int64_t r674 = 7;
    int64_t r675 = test_gt(r673, r674);
    caesar_print_int(r675);
    int64_t r677 = 5;
    int64_t r678 = 5;
    int64_t r679 = test_ge(r677, r678);
    caesar_print_int(r679);
    int64_t r681 = 3;
    int64_t r682 = 7;
    int64_t r683 = test_ge(r681, r682);
    caesar_print_int(r683);
    const char* r685 = "TEST 18: All Arithmetic with Types";
    caesar_print_str(r685);
    int64_t r704 = 10;
    int64_t r705 = 5;
    int64_t r706 = test_add(r704, r705);
    caesar_print_int(r706);
    int64_t r708 = 10;
    int64_t r709 = 5;
    int64_t r710 = test_sub(r708, r709);
    caesar_print_int(r710);
    int64_t r712 = 10;
    int64_t r713 = 5;
    int64_t r714 = test_mul(r712, r713);
    caesar_print_int(r714);
    int64_t r716 = 10;
    int64_t r717 = 5;
    int64_t r718 = test_div(r716, r717);
    caesar_print_int(r718);
    int64_t r720 = 10;
    int64_t r721 = 3;
    int64_t r722 = test_mod(r720, r721);
    caesar_print_int(r722);
    int64_t r724 = 10;
    int64_t r725 = test_neg(r724);
    caesar_print_int(r725);
    double r727 = 10.5;
    double r728 = 2.5;
    int64_t r729 = test_add(r727, r728);
    caesar_print_int(r729);
    double r731 = 10.5;
    double r732 = 2.5;
    int64_t r733 = test_sub(r731, r732);
    caesar_print_int(r733);
    double r735 = 10.5;
    double r736 = 2.0;
    int64_t r737 = test_mul(r735, r736);
    caesar_print_int(r737);
    double r739 = 10.0;
    double r740 = 4.0;
    int64_t r741 = test_div(r739, r740);
    caesar_print_int(r741);
    int64_t r743 = 10;
    double r744 = 2.5;
    int64_t r745 = test_add(r743, r744);
    caesar_print_int(r745);
    int64_t r747 = 5;
    double r748 = 2.5;
    int64_t r749 = test_mul(r747, r748);
    caesar_print_int(r749);
    int64_t r751 = 15;
    int64_t r752 = 2;
    int64_t r753 = test_div(r751, r752);
    caesar_print_int(r753);
    const char* r755 = "TEST 19: String Functions with Multiple Params";
    caesar_print_str(r755);
    const char* r767 = "First";
    const char* r768 = "Second";
    const char* r769 = "Third";
    int64_t r770 = print_three_strings(r767, r768, r769);
    const char* r771 = "Name:";
    const char* r772 = "Alice";
    int64_t r773 = print_labeled(r771, r772);
    const char* r774 = "Age:";
    const char* r775 = "30";
    int64_t r776 = print_labeled(r774, r775);
    const char* r777 = "TEST 20: Early Returns";
    caesar_print_str(r777);
    int64_t r797 = 5;
    int64_t r798 = -r797;
    int64_t r799 = early_return_test(r798);
    caesar_print_int(r799);
    int64_t r801 = 0;
    int64_t r802 = early_return_test(r801);
    caesar_print_int(r802);
    int64_t r804 = 1;
    int64_t r805 = early_return_test(r804);
    caesar_print_int(r805);
    int64_t r807 = 2;
    int64_t r808 = early_return_test(r807);
    caesar_print_int(r808);
    int64_t r810 = 10;
    int64_t r811 = early_return_test(r810);
    caesar_print_int(r811);
    const char* r813 = "=== COMPREHENSIVE TEST SUITE COMPLETE ===";
    caesar_print_str(r813);
    const char* r815 = "All 20 test sections passed!";
    caesar_print_str(r815);
    const char* r817 = "Features tested:";
    caesar_print_str(r817);
    const char* r819 = "- Integer functions";
    caesar_print_str(r819);
    const char* r821 = "- String parameter type inference";
    caesar_print_str(r821);
    const char* r823 = "- Float literals and arithmetic";
    caesar_print_str(r823);
    const char* r825 = "- True division (float results)";
    caesar_print_str(r825);
    const char* r827 = "- Mixed type arithmetic with promotion";
    caesar_print_str(r827);
    const char* r829 = "- Recursive functions";
    caesar_print_str(r829);
    const char* r831 = "- C reserved keyword escaping";
    caesar_print_str(r831);
    const char* r833 = "- Nested and chained calls";
    caesar_print_str(r833);
    const char* r835 = "- Multiple return paths";
    caesar_print_str(r835);
    const char* r837 = "- Zero to many parameters";
    caesar_print_str(r837);
    const char* r839 = "- Complex logic and comparisons";
    caesar_print_str(r839);
    const char* r841 = "- Mutual recursion";
    caesar_print_str(r841);
    const char* r843 = "- Void functions";
    caesar_print_str(r843);
    const char* r845 = "- Deep recursion";
    caesar_print_str(r845);
    const char* r847 = "- All comparison operators";
    caesar_print_str(r847);
    const char* r849 = "- All arithmetic operators";
    caesar_print_str(r849);
    const char* r851 = "- String functions";
    caesar_print_str(r851);
    const char* r853 = "- Early returns";
    caesar_print_str(r853);
    return 0;
}
