/**
 * @file test_ir.cpp
 * @brief Tests for Caesar IR generation
 * @author J.J.G. Pleunes
 * @version 1.5.1
 */

#include "caesar/lexer.h"
#include "caesar/parser.h"
#include "caesar/ir.h"
#include "caesar/codegen.h"
#include <cassert>
#include <iostream>
#include <sstream>

void test_ir_arithmetic() {
    std::cout << "Testing IR generation for arithmetic...\n";
    
    std::string source = "x = 5 + 3";
    
    caesar::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    
    caesar::Parser parser(tokens);
    auto program = parser.parse();
    
    caesar::IRGenerator ir_gen;
    auto ir_blocks = ir_gen.generate(program.get());
    
    assert(!ir_blocks.empty());
    std::cout << "  ✓ Generated " << ir_blocks.size() << " basic blocks\n";
    
    // Check that we have at least some instructions
    int total_instructions = 0;
    for (const auto& block : ir_blocks) {
        total_instructions += block.instructions.size();
    }
    
    assert(total_instructions > 0);
    std::cout << "  ✓ Generated " << total_instructions << " IR instructions\n";
    
    std::cout << "IR Output:\n" << ir_gen.toString() << "\n";
}

void test_ir_control_flow() {
    std::cout << "Testing IR generation for control flow...\n";
    
    std::string source = R"(
if x > 5:
    y = 10
else:
    y = 20
)";
    
    caesar::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    
    caesar::Parser parser(tokens);
    auto program = parser.parse();
    
    caesar::IRGenerator ir_gen;
    auto ir_blocks = ir_gen.generate(program.get());
    
    // Should have multiple blocks for if/else
    assert(ir_blocks.size() >= 3);  // entry, else, endif
    std::cout << "  ✓ Generated " << ir_blocks.size() << " basic blocks for if/else\n";
    
    std::cout << "IR Output:\n" << ir_gen.toString() << "\n";
}

void test_ir_function() {
    std::cout << "Testing IR generation for functions...\n";
    
    std::string source = R"(
def add(a, b):
    return a + b

result = add(5, 3)
)";
    
    caesar::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    
    caesar::Parser parser(tokens);
    auto program = parser.parse();
    
    caesar::IRGenerator ir_gen;
    auto ir_blocks = ir_gen.generate(program.get());
    
    assert(!ir_blocks.empty());
    std::cout << "  ✓ Generated IR for function definition and call\n";
    
    std::cout << "IR Output:\n" << ir_gen.toString() << "\n";
}

void test_codegen_bytecode() {
    std::cout << "Testing bytecode generation...\n";
    
    std::string source = "x = 10 + 5";
    
    caesar::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    
    caesar::Parser parser(tokens);
    auto program = parser.parse();
    
    caesar::IRGenerator ir_gen;
    auto ir_blocks = ir_gen.generate(program.get());
    
    auto codegen = caesar::CodeGeneratorFactory::create(caesar::TargetArch::BYTECODE);
    std::string bytecode = codegen->generate(ir_blocks);
    
    assert(!bytecode.empty());
    std::cout << "  ✓ Generated bytecode\n";
    std::cout << "Bytecode:\n" << bytecode << "\n";
}

void test_codegen_c() {
    std::cout << "Testing C code generation...\n";
    
    std::string source = "x = 10 + 5";
    
    caesar::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    
    caesar::Parser parser(tokens);
    auto program = parser.parse();
    
    caesar::IRGenerator ir_gen;
    auto ir_blocks = ir_gen.generate(program.get());
    
    auto codegen = caesar::CodeGeneratorFactory::createCGenerator();
    std::string c_code = codegen->generate(ir_blocks);
    
    assert(!c_code.empty());
    assert(c_code.find("#include") != std::string::npos);
    assert(c_code.find("int main()") != std::string::npos);
    
    std::cout << "  ✓ Generated valid C code\n";
    std::cout << "C Code:\n" << c_code << "\n";
}

void test_codegen_x86() {
    std::cout << "Testing x86-64 assembly generation...\n";
    
    std::string source = "x = 10 + 5";
    
    caesar::Lexer lexer(source);
    auto tokens = lexer.tokenize();
    
    caesar::Parser parser(tokens);
    auto program = parser.parse();
    
    caesar::IRGenerator ir_gen;
    auto ir_blocks = ir_gen.generate(program.get());
    
    auto codegen = caesar::CodeGeneratorFactory::create(caesar::TargetArch::X86_64);
    std::string asm_code = codegen->generate(ir_blocks);
    
    assert(!asm_code.empty());
    assert(asm_code.find("section .text") != std::string::npos);
    
    std::cout << "  ✓ Generated x86-64 assembly\n";
    std::cout << "Assembly:\n" << asm_code << "\n";
}

int main() {
    std::cout << "=== Caesar IR and Code Generation Tests ===\n\n";
    
    try {
        test_ir_arithmetic();
        std::cout << "\n";
        
        test_ir_control_flow();
        std::cout << "\n";
        
        test_ir_function();
        std::cout << "\n";
        
        test_codegen_bytecode();
        std::cout << "\n";
        
        test_codegen_c();
        std::cout << "\n";
        
        test_codegen_x86();
        std::cout << "\n";
        
        std::cout << "=== All IR tests passed! ===\n";
        return 0;
        
    } catch (const std::exception& e) {
        std::cerr << "Test failed: " << e.what() << "\n";
        return 1;
    }
}
