/**
 * @file codegen.cpp
 * @brief Caesar Code Generator implementation
 * @author J.J.G. Pleunes
 * @version 1.5.1
 */

#include "caesar/codegen.h"
#include <iomanip>

namespace caesar {

// ============================================================================
// Bytecode Generator
// ============================================================================

void BytecodeGenerator::emitByte(uint8_t byte) {
    output << std::hex << std::setw(2) << std::setfill('0') << (int)byte << " ";
}

void BytecodeGenerator::emitOpcode(const std::string& opcode) {
    output << opcode << " ";
}

void BytecodeGenerator::emitOperand(const IROperand& operand) {
    output << operand.toString() << " ";
}

std::string BytecodeGenerator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    output << "; Caesar Bytecode\n";
    output << "; Generated by Caesar Compiler v1.5.1\n\n";
    
    for (const auto& block : blocks) {
        if (!block.label.empty()) {
            output << block.label << ":\n";
            label_positions[block.label] = stack_size;
        }
        
        for (const auto& instr : block.instructions) {
            output << "  " << opcodeToString(instr.opcode);
            
            if (instr.dest.type != IROperandType::NONE) {
                output << " " << instr.dest.toString();
            }
            if (instr.src1.type != IROperandType::NONE) {
                output << ", " << instr.src1.toString();
            }
            if (instr.src2.type != IROperandType::NONE) {
                output << ", " << instr.src2.toString();
            }
            
            output << "\n";
        }
    }
    
    return output.str();
}

// ============================================================================
// x86-64 Assembly Generator
// ============================================================================

void X86_64Generator::emitPrologue() {
    output << "    ; Function prologue\n";
    output << "    push rbp\n";
    output << "    mov rbp, rsp\n";
    output << "    sub rsp, 64      ; Allocate stack space\n\n";
}

void X86_64Generator::emitEpilogue() {
    output << "\n    ; Function epilogue\n";
    output << "    mov rsp, rbp\n";
    output << "    pop rbp\n";
    output << "    ret\n";
}

std::string X86_64Generator::allocateRegister(const std::string& virtual_reg) {
    // Simple register allocation - map virtual registers to x86-64 registers
    static const std::vector<std::string> physical_regs = {
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "r8", "r9", "r10", "r11"
    };
    
    auto it = register_map.find(virtual_reg);
    if (it != register_map.end()) {
        return it->second;
    }
    
    // Allocate new register
    int reg_idx = register_map.size() % physical_regs.size();
    std::string physical = physical_regs[reg_idx];
    register_map[virtual_reg] = physical;
    return physical;
}

void X86_64Generator::emitInstruction(const IRInstruction& instr) {
    std::string dest_reg = instr.dest.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.dest.value) : "";
    std::string src1_reg = instr.src1.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.src1.value) : "";
    std::string src2_reg = instr.src2.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.src2.value) : "";
    
    switch (instr.opcode) {
        case IROpcode::LOAD_CONST:
            if (instr.src1.type == IROperandType::CONSTANT) {
                output << "    mov " << dest_reg << ", " << instr.src1.value << "\n";
            }
            break;
            
        case IROpcode::ADD:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    add " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::SUB:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    sub " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::MUL:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    imul " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::DIV:
            output << "    mov rax, " << src1_reg << "\n";
            output << "    cqo\n";
            output << "    idiv " << src2_reg << "\n";
            output << "    mov " << dest_reg << ", rax\n";
            break;
            
        case IROpcode::NEG:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    neg " << dest_reg << "\n";
            break;
            
        case IROpcode::EQ:
            output << "    cmp " << src1_reg << ", " << src2_reg << "\n";
            output << "    sete al\n";
            output << "    movzx " << dest_reg << ", al\n";
            break;
            
        case IROpcode::LT:
            output << "    cmp " << src1_reg << ", " << src2_reg << "\n";
            output << "    setl al\n";
            output << "    movzx " << dest_reg << ", al\n";
            break;
            
        case IROpcode::JUMP:
            output << "    jmp " << instr.dest.value << "\n";
            break;
            
        case IROpcode::JUMP_IF_FALSE:
            output << "    test " << src1_reg << ", " << src1_reg << "\n";
            output << "    jz " << instr.dest.value << "\n";
            break;
            
        case IROpcode::RETURN:
            if (instr.dest.type == IROperandType::REGISTER) {
                output << "    mov rax, " << dest_reg << "\n";
            }
            emitEpilogue();
            break;
            
        default:
            output << "    ; " << opcodeToString(instr.opcode) << " (not implemented)\n";
    }
}

std::string X86_64Generator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    register_map.clear();
    
    output << "; Caesar x86-64 Assembly\n";
    output << "; Generated by Caesar Compiler v1.5.1\n\n";
    output << "section .text\n";
    output << "global _start\n\n";
    output << "_start:\n";
    
    emitPrologue();
    
    for (const auto& block : blocks) {
        if (!block.label.empty() && block.label != "entry") {
            output << "\n" << block.label << ":\n";
        }
        
        for (const auto& instr : block.instructions) {
            emitInstruction(instr);
        }
    }
    
    output << "\n    ; Exit program\n";
    output << "    mov rax, 60      ; sys_exit\n";
    output << "    xor rdi, rdi     ; exit code 0\n";
    output << "    syscall\n";
    
    return output.str();
}

// ============================================================================
// C Code Generator (Transpiler)
// ============================================================================

std::string CCodeGenerator::indent() const {
    return std::string(indent_level * 4, ' ');
}

void CCodeGenerator::emitLine(const std::string& line) {
    output << indent() << line << "\n";
}

std::string CCodeGenerator::convertConstant(const std::string& value) const {
    // Convert Caesar constants to C constants
    if (value == "#True" || value == "True") return "true";
    if (value == "#False" || value == "False") return "false";
    if (value == "#None" || value == "None") return "0";  // None maps to 0 in C
    
    // Remove # prefix if present
    if (!value.empty() && value[0] == '#') {
        return value.substr(1);
    }
    
    return value;
}

bool CCodeGenerator::isStringLiteral(const std::string& value) const {
    return !value.empty() && value[0] == '"' && value[value.length()-1] == '"';
}

void CCodeGenerator::emitInstruction(const IRInstruction& instr) {
    switch (instr.opcode) {
        case IROpcode::LOAD_CONST: {
            std::string converted_value = convertConstant(instr.src1.value);
            // Determine type based on value and track it
            std::string type;
            if (converted_value == "true" || converted_value == "false") {
                type = "bool";
                emitLine("bool " + instr.dest.value + " = " + converted_value + ";");
            } else if (isStringLiteral(converted_value)) {
                type = "const char*";
                emitLine("const char* " + instr.dest.value + " = " + converted_value + ";");
            } else {
                type = "int64_t";
                emitLine("int64_t " + instr.dest.value + " = " + converted_value + ";");
            }
            variable_types[instr.dest.value] = type;
            break;
        }
            
        case IROpcode::GET_VAR: {
            // Use the type of the source variable if known
            auto it = variable_types.find(instr.src1.value);
            std::string type = (it != variable_types.end()) ? it->second : "int64_t";
            emitLine(type + " " + instr.dest.value + " = " + instr.src1.value + ";");
            variable_types[instr.dest.value] = type;
            break;
        }
            
        case IROpcode::SET_VAR: {
            // Get the type of the source register
            auto it = variable_types.find(instr.src1.value);
            std::string type = (it != variable_types.end()) ? it->second : "int64_t";
            
            // Declare variable if not yet declared
            if (variable_types.find(instr.dest.value) == variable_types.end()) {
                emitLine(type + " " + instr.dest.value + ";");
                variable_types[instr.dest.value] = type;
            }
            emitLine(instr.dest.value + " = " + instr.src1.value + ";");
            break;
        }
            
        case IROpcode::ADD:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " + " + instr.src2.value + ";");
            break;
            
        case IROpcode::SUB:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " - " + instr.src2.value + ";");
            break;
            
        case IROpcode::MUL:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " * " + instr.src2.value + ";");
            break;
            
        case IROpcode::DIV:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " / " + instr.src2.value + ";");
            break;
            
        case IROpcode::MOD:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " % " + instr.src2.value + ";");
            break;
            
        case IROpcode::NEG:
            emitLine("int64_t " + instr.dest.value + " = -" + instr.src1.value + ";");
            break;
            
        case IROpcode::EQ:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " == " + instr.src2.value + ";");
            break;
            
        case IROpcode::NE:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " != " + instr.src2.value + ";");
            break;
            
        case IROpcode::LT:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " < " + instr.src2.value + ";");
            break;
            
        case IROpcode::LE:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " <= " + instr.src2.value + ";");
            break;
            
        case IROpcode::GT:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " > " + instr.src2.value + ";");
            break;
            
        case IROpcode::GE:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " >= " + instr.src2.value + ";");
            break;
            
        case IROpcode::AND:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " && " + instr.src2.value + ";");
            break;
            
        case IROpcode::OR:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " || " + instr.src2.value + ";");
            break;
            
        case IROpcode::NOT:
            emitLine("bool " + instr.dest.value + " = !" + instr.src1.value + ";");
            break;
            
        case IROpcode::JUMP:
            emitLine("goto " + instr.dest.value + ";");
            break;
            
        case IROpcode::JUMP_IF_TRUE:
            emitLine("if (" + instr.src1.value + ") goto " + instr.dest.value + ";");
            break;
            
        case IROpcode::JUMP_IF_FALSE:
            emitLine("if (!" + instr.src1.value + ") goto " + instr.dest.value + ";");
            break;
            
        case IROpcode::PARAM:
            // For now, just emit a comment - proper function calls need more context
            // PARAM uses src1 as the parameter value, not dest
            if (instr.dest.type != IROperandType::NONE) {
                emitLine("// PARAM " + instr.dest.value);
            }
            break;
            
        case IROpcode::CALL:
            // For now, just emit a comment - proper function calls need more context
            if (instr.src1.value == "print") {
                // Special handling for print - this is incomplete
                emitLine("// CALL print (not fully implemented)");
            } else {
                emitLine("// CALL " + instr.src1.value + " (not fully implemented)");
            }
            break;
            
        case IROpcode::RETURN:
            if (instr.dest.type != IROperandType::NONE) {
                emitLine("return " + instr.dest.value + ";");
            } else {
                emitLine("return 0;");
            }
            break;
            
        case IROpcode::PRINT:
            emitLine("printf(\"%lld\\n\", (long long)" + instr.dest.value + ");");
            break;
            
        default:
            emitLine("// " + opcodeToString(instr.opcode) + " (not implemented)");
    }
}

std::string CCodeGenerator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    
    output << "// Caesar C Code\n";
    output << "// Generated by Caesar Compiler v1.5.1\n\n";
    output << "#include <stdio.h>\n";
    output << "#include <stdint.h>\n";
    output << "#include <stdbool.h>\n\n";
    output << "int main() {\n";
    
    indent_level = 1;
    
    for (const auto& block : blocks) {
        if (!block.label.empty() && block.label != "entry") {
            indent_level = 0;
            output << block.label << ":\n";
            indent_level = 1;
        }
        
        for (const auto& instr : block.instructions) {
            emitInstruction(instr);
        }
    }
    
    indent_level = 0;
    output << "}\n";
    
    return output.str();
}

} // namespace caesar
