/**
 * @file codegen.cpp
 * @brief Caesar Code Generator implementation
 * @author J.J.G. Pleunes
 * @version 1.5.1
 */

#include "caesar/codegen.h"
#include <iomanip>

namespace caesar {

// ============================================================================
// Bytecode Generator
// ============================================================================

void BytecodeGenerator::emitByte(uint8_t byte) {
    output << std::hex << std::setw(2) << std::setfill('0') << (int)byte << " ";
}

void BytecodeGenerator::emitOpcode(const std::string& opcode) {
    output << opcode << " ";
}

void BytecodeGenerator::emitOperand(const IROperand& operand) {
    output << operand.toString() << " ";
}

std::string BytecodeGenerator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    output << "; Caesar Bytecode\n";
    output << "; Generated by Caesar Compiler v1.5.1\n\n";
    
    for (const auto& block : blocks) {
        if (!block.label.empty()) {
            output << block.label << ":\n";
            label_positions[block.label] = stack_size;
        }
        
        for (const auto& instr : block.instructions) {
            output << "  " << opcodeToString(instr.opcode);
            
            if (instr.dest.type != IROperandType::NONE) {
                output << " " << instr.dest.toString();
            }
            if (instr.src1.type != IROperandType::NONE) {
                output << ", " << instr.src1.toString();
            }
            if (instr.src2.type != IROperandType::NONE) {
                output << ", " << instr.src2.toString();
            }
            
            output << "\n";
        }
    }
    
    return output.str();
}

// ============================================================================
// x86-64 Assembly Generator
// ============================================================================

void X86_64Generator::emitPrologue() {
    output << "    ; Function prologue\n";
    output << "    push rbp\n";
    output << "    mov rbp, rsp\n";
    output << "    sub rsp, 64      ; Allocate stack space\n\n";
}

void X86_64Generator::emitEpilogue() {
    output << "\n    ; Function epilogue\n";
    output << "    mov rsp, rbp\n";
    output << "    pop rbp\n";
    output << "    ret\n";
}

std::string X86_64Generator::allocateRegister(const std::string& virtual_reg) {
    // Simple register allocation - map virtual registers to x86-64 registers
    static const std::vector<std::string> physical_regs = {
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "r8", "r9", "r10", "r11"
    };
    
    auto it = register_map.find(virtual_reg);
    if (it != register_map.end()) {
        return it->second;
    }
    
    // Allocate new register
    int reg_idx = register_map.size() % physical_regs.size();
    std::string physical = physical_regs[reg_idx];
    register_map[virtual_reg] = physical;
    return physical;
}

void X86_64Generator::emitInstruction(const IRInstruction& instr) {
    std::string dest_reg = instr.dest.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.dest.value) : "";
    std::string src1_reg = instr.src1.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.src1.value) : "";
    std::string src2_reg = instr.src2.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.src2.value) : "";
    
    switch (instr.opcode) {
        case IROpcode::LOAD_CONST:
            if (instr.src1.type == IROperandType::CONSTANT) {
                output << "    mov " << dest_reg << ", " << instr.src1.value << "\n";
            }
            break;
            
        case IROpcode::ADD:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    add " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::SUB:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    sub " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::MUL:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    imul " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::DIV:
            output << "    mov rax, " << src1_reg << "\n";
            output << "    cqo\n";
            output << "    idiv " << src2_reg << "\n";
            output << "    mov " << dest_reg << ", rax\n";
            break;
            
        case IROpcode::NEG:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    neg " << dest_reg << "\n";
            break;
            
        case IROpcode::EQ:
            output << "    cmp " << src1_reg << ", " << src2_reg << "\n";
            output << "    sete al\n";
            output << "    movzx " << dest_reg << ", al\n";
            break;
            
        case IROpcode::LT:
            output << "    cmp " << src1_reg << ", " << src2_reg << "\n";
            output << "    setl al\n";
            output << "    movzx " << dest_reg << ", al\n";
            break;
            
        case IROpcode::JUMP:
            output << "    jmp " << instr.dest.value << "\n";
            break;
            
        case IROpcode::JUMP_IF_FALSE:
            output << "    test " << src1_reg << ", " << src1_reg << "\n";
            output << "    jz " << instr.dest.value << "\n";
            break;
            
        case IROpcode::RETURN:
            if (instr.dest.type == IROperandType::REGISTER) {
                output << "    mov rax, " << dest_reg << "\n";
            }
            emitEpilogue();
            break;
            
        default:
            output << "    ; " << opcodeToString(instr.opcode) << " (not implemented)\n";
    }
}

std::string X86_64Generator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    register_map.clear();
    
    output << "; Caesar x86-64 Assembly\n";
    output << "; Generated by Caesar Compiler v1.5.1\n\n";
    output << "section .text\n";
    output << "global _start\n\n";
    output << "_start:\n";
    
    emitPrologue();
    
    for (const auto& block : blocks) {
        if (!block.label.empty() && block.label != "entry") {
            output << "\n" << block.label << ":\n";
        }
        
        for (const auto& instr : block.instructions) {
            emitInstruction(instr);
        }
    }
    
    output << "\n    ; Exit program\n";
    output << "    mov rax, 60      ; sys_exit\n";
    output << "    xor rdi, rdi     ; exit code 0\n";
    output << "    syscall\n";
    
    return output.str();
}

// ============================================================================
// C Code Generator (Transpiler)
// ============================================================================

std::string CCodeGenerator::indent() const {
    return std::string(indent_level * 4, ' ');
}

void CCodeGenerator::emitLine(const std::string& line) {
    output << indent() << line << "\n";
}

std::string CCodeGenerator::convertConstant(const std::string& value) const {
    // Convert Caesar constants to C constants
    if (value == "#True" || value == "True") return "true";
    if (value == "#False" || value == "False") return "false";
    if (value == "#None" || value == "None") return "0";  // None maps to 0 in C
    
    // Remove # prefix if present
    if (!value.empty() && value[0] == '#') {
        return value.substr(1);
    }
    
    return value;
}

bool CCodeGenerator::isStringLiteral(const std::string& value) const {
    return !value.empty() && value[0] == '"' && value[value.length()-1] == '"';
}

bool CCodeGenerator::isFloatLiteral(const std::string& value) const {
    // Check if value contains a decimal point and is a valid number
    if (value.empty() || value.find('"') != std::string::npos) return false;
    
    size_t dot_pos = value.find('.');
    if (dot_pos == std::string::npos) return false;
    
    // Basic validation: check if characters are digits, dot, or negative sign
    for (size_t i = 0; i < value.length(); ++i) {
        char c = value[i];
        if (!std::isdigit(c) && c != '.' && c != '-' && c != '+') {
            return false;
        }
    }
    
    // Ensure there's at least one digit before or after the dot
    if (dot_pos > 0 && dot_pos < value.length() - 1) {
        return true;
    }
    
    return false;
}

std::string CCodeGenerator::getResultType(const std::string& type1, const std::string& type2) const {
    // Determine result type for binary operations
    // If either operand is double, result is double
    if (type1 == "double" || type2 == "double") return "double";
    
    // String arithmetic is not valid - this indicates a potential error
    // For now, emit a comment warning and fall back to int64_t
    // In production, this should throw an error
    if (type1 == "const char*" || type2 == "const char*") {
        // TODO: Add proper error handling for invalid string arithmetic
        return "int64_t";  // Fallback for now
    }
    
    // If either is bool, treat as int64_t
    if (type1 == "bool" || type2 == "bool") return "int64_t";
    // Both int64_t
    return "int64_t";
}

std::string CCodeGenerator::sanitizeName(const std::string& name) const {
    // Remove IR prefixes (%, $, @, #) to make valid C identifiers
    std::string result = name;
    if (!result.empty() && (result[0] == '%' || result[0] == '$' || result[0] == '@' || result[0] == '#')) {
        result = result.substr(1);
    }
    // Replace any remaining invalid characters
    for (char& c : result) {
        if (!std::isalnum(c) && c != '_') {
            c = '_';
        }
    }
    return result;
}

std::string CCodeGenerator::getCaesarType(const std::string& ir_operand) const {
    // Determine Caesar type for runtime based on IR operand
    auto it = variable_types.find(ir_operand);
    if (it != variable_types.end()) {
        const std::string& type = it->second;
        if (type == "int64_t") return "CAESAR_INT";
        if (type == "double") return "CAESAR_FLOAT";
        if (type == "const char*") return "CAESAR_STRING";
        if (type == "bool") return "CAESAR_BOOL";
    }
    
    // Try to infer from the value itself
    std::string value = ir_operand;
    // Remove # prefix if present
    if (!value.empty() && value[0] == '#') {
        value = value.substr(1);
    }
    
    if (value == "True" || value == "False") return "CAESAR_BOOL";
    if (isStringLiteral(value)) return "CAESAR_STRING";
    if (isFloatLiteral(value)) return "CAESAR_FLOAT";
    
    return "CAESAR_INT";  // Default to int
}

std::string CCodeGenerator::escapeCString(const std::string& str) const {
    // Escape special characters for C string literals
    // Input contains literal characters (e.g., actual newline) that need escaping
    // The lexer converts \n to actual newline, we convert back to \n for C
    if (str.length() < 2 || (str[0] != '"' && str[0] != '\'')) {
        return str;  // Not a string literal
    }
    
    std::string result;
    result += str[0];  // Opening quote
    
    // Process the content between quotes
    for (size_t i = 1; i < str.length() - 1; ++i) {
        char c = str[i];
        switch (c) {
            case '\n': result += "\\n"; break;
            case '\t': result += "\\t"; break;
            case '\r': result += "\\r"; break;
            case '\\': result += "\\\\"; break;
            case '\"': result += "\\\""; break;
            case '\'': result += "\\'"; break;
            case '\0': result += "\\0"; break;
            default: result += c; break;
        }
    }
    
    result += str[str.length() - 1];  // Closing quote
    return result;
}

bool CCodeGenerator::isFunctionBlock(const BasicBlock& block) const {
    // Function blocks have labels like "func_name"
    // Entry block and other non-function blocks don't match this pattern
    return !block.label.empty() 
        && block.label != "entry"
        && block.label.substr(0, 5) == "func_";
}

void CCodeGenerator::registerFunction(const BasicBlock& block) {
    FunctionInfo info;
    info.name = block.label;  // e.g., "func_add"
    info.return_type = "int64_t";  // Default return type
    
    // Extract parameters from DECLARE instructions and function body
    // Stop at first RETURN instruction (marks end of function)
    for (const auto& instr : block.instructions) {
        if (instr.opcode == IROpcode::DECLARE) {
            info.parameters.push_back(instr.dest.value);
        }
        
        info.body.push_back(instr);
        
        // Stop after first RETURN - this marks the end of the function
        if (instr.opcode == IROpcode::RETURN) {
            break;
        }
    }
    
    function_registry[info.name] = info;
}

void CCodeGenerator::emitFunctionDefinition(const FunctionInfo& func) {
    // Generate function signature
    output << func.return_type << " " << sanitizeName(func.name) << "(";
    
    // Parameters
    for (size_t i = 0; i < func.parameters.size(); i++) {
        if (i > 0) output << ", ";
        output << "int64_t " << sanitizeName(func.parameters[i]);
    }
    output << ") {\n";
    
    // Function body
    indent_level = 1;
    in_function = true;
    current_function_name = func.name;
    
    // Process instructions (skip DECLARE, we handled those in parameters)
    for (const auto& instr : func.body) {
        if (instr.opcode != IROpcode::DECLARE) {
            emitInstruction(instr);
        }
    }
    
    in_function = false;
    indent_level = 0;
    output << "}\n\n";
}

void CCodeGenerator::emitFunctionCall(const std::string& func_name, 
                                       const std::vector<std::string>& args, 
                                       const std::string& dest_reg) {
    // Generate function call: dest = func(arg1, arg2, ...)
    std::string sanitized_dest = sanitizeName(dest_reg);
    std::string sanitized_func = sanitizeName("func_" + func_name);
    
    // Build complete call line before emitting
    std::string call_line = "int64_t " + sanitized_dest + " = " + sanitized_func + "(";
    
    // Arguments
    for (size_t i = 0; i < args.size(); i++) {
        if (i > 0) call_line += ", ";
        call_line += sanitizeName(args[i]);
    }
    
    call_line += ");";
    emitLine(call_line);
    
    variable_types[dest_reg] = "int64_t";
}

void CCodeGenerator::emitInstruction(const IRInstruction& instr) {
    switch (instr.opcode) {
        case IROpcode::LOAD_CONST: {
            std::string converted_value = convertConstant(instr.src1.value);
            std::string dest_name = sanitizeName(instr.dest.value);
            // Determine type based on value and track it
            std::string type;
            if (converted_value == "true" || converted_value == "false") {
                type = "bool";
                emitLine("bool " + dest_name + " = " + converted_value + ";");
            } else if (isStringLiteral(converted_value)) {
                type = "const char*";
                // Escape the string literal for C
                std::string escaped = escapeCString(converted_value);
                emitLine("const char* " + dest_name + " = " + escaped + ";");
            } else if (isFloatLiteral(converted_value)) {
                type = "double";
                emitLine("double " + dest_name + " = " + converted_value + ";");
            } else {
                type = "int64_t";
                emitLine("int64_t " + dest_name + " = " + converted_value + ";");
            }
            variable_types[instr.dest.value] = type;
            break;
        }
            
        case IROpcode::GET_VAR: {
            // Use the type of the source variable if known
            auto it = variable_types.find(instr.src1.value);
            std::string type = (it != variable_types.end()) ? it->second : "int64_t";
            std::string dest_name = sanitizeName(instr.dest.value);
            std::string src_name = sanitizeName(instr.src1.value);
            emitLine(type + " " + dest_name + " = " + src_name + ";");
            variable_types[instr.dest.value] = type;
            break;
        }
            
        case IROpcode::SET_VAR: {
            // Get the type of the source register
            auto it = variable_types.find(instr.src1.value);
            std::string type = (it != variable_types.end()) ? it->second : "int64_t";
            std::string dest_name = sanitizeName(instr.dest.value);
            std::string src_name = sanitizeName(instr.src1.value);
            
            // Declare and initialize in one line if not yet declared
            // This avoids uninitialized variable warnings and is clearer
            if (variable_types.find(instr.dest.value) == variable_types.end()) {
                emitLine(type + " " + dest_name + " = " + src_name + ";");
                variable_types[instr.dest.value] = type;
            } else {
                // Variable already declared, just assign
                emitLine(dest_name + " = " + src_name + ";");
            }
            break;
        }
            
        case IROpcode::ADD: {
            auto it1 = variable_types.find(instr.src1.value);
            auto it2 = variable_types.find(instr.src2.value);
            std::string type1 = (it1 != variable_types.end()) ? it1->second : "int64_t";
            std::string type2 = (it2 != variable_types.end()) ? it2->second : "int64_t";
            std::string result_type = getResultType(type1, type2);
            emitLine(result_type + " " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " + " + sanitizeName(instr.src2.value) + ";");
            variable_types[instr.dest.value] = result_type;
            break;
        }
            
        case IROpcode::SUB: {
            auto it1 = variable_types.find(instr.src1.value);
            auto it2 = variable_types.find(instr.src2.value);
            std::string type1 = (it1 != variable_types.end()) ? it1->second : "int64_t";
            std::string type2 = (it2 != variable_types.end()) ? it2->second : "int64_t";
            std::string result_type = getResultType(type1, type2);
            emitLine(result_type + " " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " - " + sanitizeName(instr.src2.value) + ";");
            variable_types[instr.dest.value] = result_type;
            break;
        }
            
        case IROpcode::MUL: {
            auto it1 = variable_types.find(instr.src1.value);
            auto it2 = variable_types.find(instr.src2.value);
            std::string type1 = (it1 != variable_types.end()) ? it1->second : "int64_t";
            std::string type2 = (it2 != variable_types.end()) ? it2->second : "int64_t";
            std::string result_type = getResultType(type1, type2);
            emitLine(result_type + " " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " * " + sanitizeName(instr.src2.value) + ";");
            variable_types[instr.dest.value] = result_type;
            break;
        }
            
        case IROpcode::DIV: {
            auto it1 = variable_types.find(instr.src1.value);
            auto it2 = variable_types.find(instr.src2.value);
            std::string type1 = (it1 != variable_types.end()) ? it1->second : "int64_t";
            std::string type2 = (it2 != variable_types.end()) ? it2->second : "int64_t";
            std::string result_type = getResultType(type1, type2);
            emitLine(result_type + " " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " / " + sanitizeName(instr.src2.value) + ";");
            variable_types[instr.dest.value] = result_type;
            break;
        }
            
        case IROpcode::MOD: {
            // Modulo typically only works with integers, so keep as int64_t
            emitLine("int64_t " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " % " + sanitizeName(instr.src2.value) + ";");
            variable_types[instr.dest.value] = "int64_t";
            break;
        }
            
        case IROpcode::NEG: {
            auto it = variable_types.find(instr.src1.value);
            std::string type = (it != variable_types.end()) ? it->second : "int64_t";
            // Keep same type for negation
            if (type == "double") {
                emitLine("double " + sanitizeName(instr.dest.value) + " = -" + sanitizeName(instr.src1.value) + ";");
            } else {
                emitLine("int64_t " + sanitizeName(instr.dest.value) + " = -" + sanitizeName(instr.src1.value) + ";");
            }
            variable_types[instr.dest.value] = type;
            break;
        }
            
        case IROpcode::EQ:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " == " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::NE:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " != " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::LT:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " < " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::LE:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " <= " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::GT:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " > " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::GE:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " >= " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::AND:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " && " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::OR:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = " + sanitizeName(instr.src1.value) + " || " + sanitizeName(instr.src2.value) + ";");
            break;
            
        case IROpcode::NOT:
            emitLine("bool " + sanitizeName(instr.dest.value) + " = !" + sanitizeName(instr.src1.value) + ";");
            break;
            
        case IROpcode::JUMP:
            emitLine("goto " + sanitizeName(instr.dest.value) + ";");
            break;
            
        case IROpcode::JUMP_IF_TRUE:
            emitLine("if (" + sanitizeName(instr.src1.value) + ") goto " + sanitizeName(instr.dest.value) + ";");
            break;
            
        case IROpcode::JUMP_IF_FALSE:
            emitLine("if (!" + sanitizeName(instr.src1.value) + ") goto " + sanitizeName(instr.dest.value) + ";");
            break;
            
        case IROpcode::PARAM:
            // Track parameters for the next CALL instruction
            // PARAM instruction has the value in dest (based on IR generation)
            if (instr.dest.type != IROperandType::NONE) {
                pending_params.push_back(instr.dest.value);
            }
            break;
            
        case IROpcode::CALL: {
            // Handle built-in function calls
            std::string func_name = sanitizeName(instr.src1.value);
            
            if (func_name == "print") {
                // Generate call to caesar_print runtime function
                int argc = pending_params.size();
                if (argc > 0) {
                    emitLine("{");
                    indent_level++;
                    emitLine("CaesarValue args[" + std::to_string(argc) + "];");
                    
                    for (int i = 0; i < argc; i++) {
                        std::string param = pending_params[i];
                        std::string caesar_type = getCaesarType(param);
                        std::string sanitized = sanitizeName(param);
                        
                        emitLine("args[" + std::to_string(i) + "].type = " + caesar_type + ";");
                        
                        // Set the appropriate union member based on type
                        if (caesar_type == "CAESAR_INT") {
                            emitLine("args[" + std::to_string(i) + "].data.i = " + sanitized + ";");
                        } else if (caesar_type == "CAESAR_FLOAT") {
                            emitLine("args[" + std::to_string(i) + "].data.f = " + sanitized + ";");
                        } else if (caesar_type == "CAESAR_STRING") {
                            emitLine("args[" + std::to_string(i) + "].data.s = " + sanitized + ";");
                        } else if (caesar_type == "CAESAR_BOOL") {
                            emitLine("args[" + std::to_string(i) + "].data.b = " + sanitized + ";");
                        }
                    }
                    
                    emitLine("caesar_print(" + std::to_string(argc) + ", args);");
                    indent_level--;
                    emitLine("}");
                } else {
                    // Print with no arguments - just print newline
                    emitLine("caesar_print(0, NULL);");
                }
                pending_params.clear();
            } else if (func_name == "len") {
                // Generate call to caesar_len runtime function
                if (pending_params.size() >= 1) {
                    // Take the last parameter (most recent one pushed)
                    std::string param = pending_params.back();
                    pending_params.pop_back();  // Remove it from the list
                    
                    bool had_other_params = !pending_params.empty();  // Check if there were other params
                    
                    std::string caesar_type = getCaesarType(param);
                    std::string sanitized = sanitizeName(param);
                    std::string result = sanitizeName(instr.dest.value);
                    
                    // Create a temp variable name for the arg
                    static int len_counter = 0;
                    std::string temp_arg = "len_arg_" + std::to_string(len_counter++);
                    
                    emitLine("CaesarValue " + temp_arg + ";");
                    emitLine(temp_arg + ".type = " + caesar_type + ";");
                    
                    if (caesar_type == "CAESAR_INT") {
                        emitLine(temp_arg + ".data.i = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_FLOAT") {
                        emitLine(temp_arg + ".data.f = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_STRING") {
                        emitLine(temp_arg + ".data.s = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_BOOL") {
                        emitLine(temp_arg + ".data.b = " + sanitized + ";");
                    }
                    
                    emitLine("int64_t " + result + " = caesar_len(&" + temp_arg + ");");
                    variable_types[instr.dest.value] = "int64_t";
                    
                    // If there were other params, this is a nested call - add result back for parent call
                    if (had_other_params) {
                        pending_params.push_back(instr.dest.value);
                    }
                } else {
                    emitLine("// ERROR: len() requires exactly 1 argument");
                    pending_params.clear();
                }
            } else if (func_name == "str") {
                // Generate call to caesar_str runtime function
                if (pending_params.size() >= 1) {
                    // Take the last parameter (most recent one pushed)
                    std::string param = pending_params.back();
                    pending_params.pop_back();  // Remove it from the list
                    
                    bool had_other_params = !pending_params.empty();  // Check if there were other params
                    
                    std::string caesar_type = getCaesarType(param);
                    std::string sanitized = sanitizeName(param);
                    std::string result = sanitizeName(instr.dest.value);
                    
                    // Create a temp variable name for the arg
                    static int str_counter = 0;
                    std::string temp_arg = "str_arg_" + std::to_string(str_counter++);
                    
                    emitLine("CaesarValue " + temp_arg + ";");
                    emitLine(temp_arg + ".type = " + caesar_type + ";");
                    
                    if (caesar_type == "CAESAR_INT") {
                        emitLine(temp_arg + ".data.i = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_FLOAT") {
                        emitLine(temp_arg + ".data.f = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_STRING") {
                        emitLine(temp_arg + ".data.s = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_BOOL") {
                        emitLine(temp_arg + ".data.b = " + sanitized + ";");
                    }
                    
                    emitLine("const char* " + result + " = caesar_str(&" + temp_arg + ");");
                    variable_types[instr.dest.value] = "const char*";
                    
                    // If there were other params, this is a nested call - add result back for parent call
                    if (had_other_params) {
                        pending_params.push_back(instr.dest.value);
                    }
                } else {
                    emitLine("// ERROR: str() requires exactly 1 argument");
                    pending_params.clear();
                }
            } else if (func_name == "int") {
                // Generate call to caesar_int runtime function
                if (pending_params.size() >= 1) {
                    // Take the last parameter (most recent one pushed)
                    std::string param = pending_params.back();
                    pending_params.pop_back();  // Remove it from the list
                    
                    bool had_other_params = !pending_params.empty();  // Check if there were other params
                    
                    std::string caesar_type = getCaesarType(param);
                    std::string sanitized = sanitizeName(param);
                    std::string result = sanitizeName(instr.dest.value);
                    
                    // Create a temp variable name for the arg
                    static int int_counter = 0;
                    std::string temp_arg = "int_arg_" + std::to_string(int_counter++);
                    
                    emitLine("CaesarValue " + temp_arg + ";");
                    emitLine(temp_arg + ".type = " + caesar_type + ";");
                    
                    if (caesar_type == "CAESAR_INT") {
                        emitLine(temp_arg + ".data.i = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_FLOAT") {
                        emitLine(temp_arg + ".data.f = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_STRING") {
                        emitLine(temp_arg + ".data.s = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_BOOL") {
                        emitLine(temp_arg + ".data.b = " + sanitized + ";");
                    }
                    
                    emitLine("int64_t " + result + " = caesar_int(&" + temp_arg + ");");
                    variable_types[instr.dest.value] = "int64_t";
                    
                    // If there were other params, this is a nested call - add result back for parent call
                    if (had_other_params) {
                        pending_params.push_back(instr.dest.value);
                    }
                } else {
                    emitLine("// ERROR: int() requires exactly 1 argument");
                    pending_params.clear();
                }
            } else if (func_name == "float") {
                // Generate call to caesar_float runtime function
                if (pending_params.size() >= 1) {
                    // Take the last parameter (most recent one pushed)
                    std::string param = pending_params.back();
                    pending_params.pop_back();  // Remove it from the list
                    
                    bool had_other_params = !pending_params.empty();  // Check if there were other params
                    
                    std::string caesar_type = getCaesarType(param);
                    std::string sanitized = sanitizeName(param);
                    std::string result = sanitizeName(instr.dest.value);
                    
                    // Create a temp variable name for the arg
                    static int float_counter = 0;
                    std::string temp_arg = "float_arg_" + std::to_string(float_counter++);
                    
                    emitLine("CaesarValue " + temp_arg + ";");
                    emitLine(temp_arg + ".type = " + caesar_type + ";");
                    
                    if (caesar_type == "CAESAR_INT") {
                        emitLine(temp_arg + ".data.i = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_FLOAT") {
                        emitLine(temp_arg + ".data.f = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_STRING") {
                        emitLine(temp_arg + ".data.s = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_BOOL") {
                        emitLine(temp_arg + ".data.b = " + sanitized + ";");
                    }
                    
                    emitLine("double " + result + " = caesar_float(&" + temp_arg + ");");
                    variable_types[instr.dest.value] = "double";
                    
                    // If there were other params, this is a nested call - add result back for parent call
                    if (had_other_params) {
                        pending_params.push_back(instr.dest.value);
                    }
                } else {
                    emitLine("// ERROR: float() requires exactly 1 argument");
                    pending_params.clear();
                }
            } else if (func_name == "abs") {
                // Generate call to caesar_abs runtime function
                if (pending_params.size() >= 1) {
                    // Take the last parameter (most recent one pushed)
                    std::string param = pending_params.back();
                    pending_params.pop_back();  // Remove it from the list
                    
                    bool had_other_params = !pending_params.empty();  // Check if there were other params
                    
                    std::string caesar_type = getCaesarType(param);
                    std::string sanitized = sanitizeName(param);
                    std::string result = sanitizeName(instr.dest.value);
                    
                    // Create a temp variable name for the arg
                    static int abs_counter = 0;
                    std::string temp_arg = "abs_arg_" + std::to_string(abs_counter++);
                    
                    emitLine("CaesarValue " + temp_arg + ";");
                    emitLine(temp_arg + ".type = " + caesar_type + ";");
                    
                    if (caesar_type == "CAESAR_INT") {
                        emitLine(temp_arg + ".data.i = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_FLOAT") {
                        emitLine(temp_arg + ".data.f = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_STRING") {
                        emitLine(temp_arg + ".data.s = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_BOOL") {
                        emitLine(temp_arg + ".data.b = " + sanitized + ";");
                    }
                    
                    emitLine("double " + result + " = caesar_abs(&" + temp_arg + ");");
                    variable_types[instr.dest.value] = "double";
                    
                    // If there were other params, this is a nested call - add result back for parent call
                    if (had_other_params) {
                        pending_params.push_back(instr.dest.value);
                    }
                } else {
                    emitLine("// ERROR: abs() requires exactly 1 argument");
                    pending_params.clear();
                }
            } else if (func_name == "type") {
                // Generate call to caesar_type runtime function
                if (pending_params.size() >= 1) {
                    // Take the last parameter (most recent one pushed)
                    std::string param = pending_params.back();
                    pending_params.pop_back();  // Remove it from the list
                    
                    bool had_other_params = !pending_params.empty();  // Check if there were other params
                    
                    std::string caesar_type = getCaesarType(param);
                    std::string sanitized = sanitizeName(param);
                    std::string result = sanitizeName(instr.dest.value);
                    
                    // Create a temp variable name for the arg
                    static int type_counter = 0;
                    std::string temp_arg = "type_arg_" + std::to_string(type_counter++);
                    
                    emitLine("CaesarValue " + temp_arg + ";");
                    emitLine(temp_arg + ".type = " + caesar_type + ";");
                    
                    if (caesar_type == "CAESAR_INT") {
                        emitLine(temp_arg + ".data.i = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_FLOAT") {
                        emitLine(temp_arg + ".data.f = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_STRING") {
                        emitLine(temp_arg + ".data.s = " + sanitized + ";");
                    } else if (caesar_type == "CAESAR_BOOL") {
                        emitLine(temp_arg + ".data.b = " + sanitized + ";");
                    }
                    
                    emitLine("const char* " + result + " = caesar_type(&" + temp_arg + ");");
                    variable_types[instr.dest.value] = "const char*";
                    
                    // If there were other params, this is a nested call - add result back for parent call
                    if (had_other_params) {
                        pending_params.push_back(instr.dest.value);
                    }
                } else {
                    emitLine("// ERROR: type() requires exactly 1 argument");
                    pending_params.clear();
                }
            } else {
                // Check if it's a user-defined function
                std::string func_label = "func_" + instr.src1.value;
                if (function_registry.count(func_label) > 0) {
                    // User-defined function call
                    std::string result_reg = sanitizeName(instr.dest.value);
                    std::string call_name = sanitizeName(func_label);
                    
                    // Build argument list from pending_params
                    std::stringstream args;
                    for (size_t i = 0; i < pending_params.size(); i++) {
                        if (i > 0) args << ", ";
                        args << sanitizeName(pending_params[i]);
                    }
                    
                    emitLine("int64_t " + result_reg + " = " + call_name + "(" + args.str() + ");");
                    variable_types[instr.dest.value] = "int64_t";
                    pending_params.clear();
                } else {
                    // Unknown function
                    emitLine("// ERROR: Unknown function: " + func_name);
                    pending_params.clear();
                }
            }
            break;
        }
            
        case IROpcode::RETURN:
            if (instr.dest.type != IROperandType::NONE) {
                emitLine("return " + instr.dest.value + ";");
            } else {
                emitLine("return 0;");
            }
            break;
            
        case IROpcode::PRINT:
            emitLine("printf(\"%lld\\n\", (long long)" + instr.dest.value + ");");
            break;
            
        default:
            emitLine("// " + opcodeToString(instr.opcode) + " (not implemented)");
    }
}

std::string CCodeGenerator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    pending_params.clear();  // Clear any previous state
    
    output << "// Caesar C Code\n";
    output << "// Generated by Caesar Compiler v1.5.1\n\n";
    output << "#include <stdio.h>\n";
    output << "#include <stdint.h>\n";
    output << "#include <stdbool.h>\n";
    // Include runtime header inline to avoid path issues
    output << "\n// Caesar Runtime Library (inline)\n";
    output << "typedef enum { CAESAR_INT, CAESAR_FLOAT, CAESAR_STRING, CAESAR_BOOL, CAESAR_NONE } CaesarType;\n";
    output << "typedef struct {\n";
    output << "    CaesarType type;\n";
    output << "    union {\n";
    output << "        int64_t i;\n";
    output << "        double f;\n";
    output << "        const char* s;\n";
    output << "        bool b;\n";
    output << "    } data;\n";
    output << "} CaesarValue;\n\n";
    output << "void caesar_print(int argc, CaesarValue* args) {\n";
    output << "    for (int i = 0; i < argc; i++) {\n";
    output << "        if (i > 0) printf(\" \");\n";
    output << "        switch (args[i].type) {\n";
    output << "            case CAESAR_INT: printf(\"%lld\", (long long)args[i].data.i); break;\n";
    output << "            case CAESAR_FLOAT: printf(\"%g\", args[i].data.f); break;\n";
    output << "            case CAESAR_STRING: printf(\"%s\", args[i].data.s); break;\n";
    output << "            case CAESAR_BOOL: printf(\"%s\", args[i].data.b ? \"True\" : \"False\"); break;\n";
    output << "            case CAESAR_NONE: printf(\"None\"); break;\n";
    output << "        }\n";
    output << "    }\n";
    output << "    printf(\"\\n\");\n";
    output << "}\n\n";
    output << "#include <string.h>\n";
    output << "#include <stdlib.h>\n";
    output << "int64_t caesar_len(CaesarValue* arg) {\n";
    output << "    switch (arg->type) {\n";
    output << "        case CAESAR_STRING: return (int64_t)strlen(arg->data.s);\n";
    output << "        case CAESAR_INT: return 1;  // Single value has length 1\n";
    output << "        case CAESAR_FLOAT: return 1;\n";
    output << "        case CAESAR_BOOL: return 1;\n";
    output << "        case CAESAR_NONE: return 0;\n";
    output << "        default: return 0;\n";
    output << "    }\n";
    output << "}\n\n";
    output << "const char* caesar_str(CaesarValue* arg) {\n";
    output << "    static char buffer[256];\n";
    output << "    switch (arg->type) {\n";
    output << "        case CAESAR_STRING: return arg->data.s;\n";
    output << "        case CAESAR_INT:\n";
    output << "            snprintf(buffer, sizeof(buffer), \"%lld\", (long long)arg->data.i);\n";
    output << "            return buffer;\n";
    output << "        case CAESAR_FLOAT:\n";
    output << "            snprintf(buffer, sizeof(buffer), \"%g\", arg->data.f);\n";
    output << "            return buffer;\n";
    output << "        case CAESAR_BOOL:\n";
    output << "            return arg->data.b ? \"True\" : \"False\";\n";
    output << "        case CAESAR_NONE:\n";
    output << "            return \"None\";\n";
    output << "        default:\n";
    output << "            return \"\";\n";
    output << "    }\n";
    output << "}\n\n";
    output << "int64_t caesar_int(CaesarValue* arg) {\n";
    output << "    switch (arg->type) {\n";
    output << "        case CAESAR_INT: return arg->data.i;\n";
    output << "        case CAESAR_FLOAT: return (int64_t)arg->data.f;  // Truncate float to int\n";
    output << "        case CAESAR_BOOL: return arg->data.b ? 1 : 0;\n";
    output << "        case CAESAR_STRING: return (int64_t)atoll(arg->data.s);  // Parse string to int\n";
    output << "        case CAESAR_NONE: return 0;\n";
    output << "        default: return 0;\n";
    output << "    }\n";
    output << "}\n\n";
    output << "double caesar_float(CaesarValue* arg) {\n";
    output << "    switch (arg->type) {\n";
    output << "        case CAESAR_INT: return (double)arg->data.i;  // Convert int to float\n";
    output << "        case CAESAR_FLOAT: return arg->data.f;  // Identity\n";
    output << "        case CAESAR_BOOL: return arg->data.b ? 1.0 : 0.0;\n";
    output << "        case CAESAR_STRING: return atof(arg->data.s);  // Parse string to float\n";
    output << "        case CAESAR_NONE: return 0.0;\n";
    output << "        default: return 0.0;\n";
    output << "    }\n";
    output << "}\n\n";
    output << "#include <math.h>\n";
    output << "double caesar_abs(CaesarValue* arg) {\n";
    output << "    switch (arg->type) {\n";
    output << "        case CAESAR_INT: return (double)(arg->data.i < 0 ? -arg->data.i : arg->data.i);\n";
    output << "        case CAESAR_FLOAT: return fabs(arg->data.f);  // Use fabs for floats\n";
    output << "        case CAESAR_BOOL: return arg->data.b ? 1.0 : 0.0;  // abs(bool) = bool as number\n";
    output << "        case CAESAR_STRING: return fabs(atof(arg->data.s));  // Parse and abs\n";
    output << "        case CAESAR_NONE: return 0.0;\n";
    output << "        default: return 0.0;\n";
    output << "    }\n";
    output << "}\n\n";
    output << "const char* caesar_type(CaesarValue* arg) {\n";
    output << "    switch (arg->type) {\n";
    output << "        case CAESAR_INT: return \"int\";\n";
    output << "        case CAESAR_FLOAT: return \"float\";\n";
    output << "        case CAESAR_STRING: return \"string\";\n";
    output << "        case CAESAR_BOOL: return \"bool\";\n";
    output << "        case CAESAR_NONE: return \"None\";\n";
    output << "        default: return \"unknown\";\n";
    output << "    }\n";
    output << "}\n\n";
    
    // PASS 1: Identify and register all functions
    function_registry.clear();
    for (const auto& block : blocks) {
        if (isFunctionBlock(block)) {
            registerFunction(block);
        }
    }
    
    // PASS 2: Generate code in proper order
    
    // Step 1: Forward declarations
    if (!function_registry.empty()) {
        output << "// Forward declarations\n";
        for (const auto& [name, info] : function_registry) {
            output << info.return_type << " " << sanitizeName(name) << "(";
            for (size_t i = 0; i < info.parameters.size(); i++) {
                if (i > 0) output << ", ";
                output << "int64_t " << sanitizeName(info.parameters[i]);
            }
            output << ");\n";
        }
        output << "\n";
    }
    
    // Step 2: Function definitions
    if (!function_registry.empty()) {
        output << "// Function implementations\n";
        for (const auto& [name, info] : function_registry) {
            emitFunctionDefinition(info);
        }
    }
    
    // Step 3: Main function
    output << "int main() {\n";
    indent_level = 1;
    
    // Clear variable types from functions - main has its own scope
    variable_types.clear();
    
    // Process blocks, skipping function code
    for (const auto& block : blocks) {
        if (isFunctionBlock(block)) {
            // This is a function block - skip instructions that are part of the function
            // Find where the function ends (at first RETURN)
            size_t func_end = 0;
            for (size_t i = 0; i < block.instructions.size(); i++) {
                if (block.instructions[i].opcode == IROpcode::RETURN) {
                    func_end = i + 1;
                    break;
                }
            }
            
            // Process remaining instructions (main code that follows the function)
            // Skip the second RETURN instruction after function RETURN
            // The IR generator emits: RETURN %r2 (function return) followed by RETURN (cleanup)
            // We need to skip this cleanup RETURN to avoid emitting "return 0;" in main
            size_t start_idx = func_end;
            if (start_idx < block.instructions.size() && 
                block.instructions[start_idx].opcode == IROpcode::RETURN) {
                start_idx++;
            }
            
            for (size_t i = start_idx; i < block.instructions.size(); i++) {
                emitInstruction(block.instructions[i]);
            }
        } else {
            // Non-function block - process normally
            if (!block.label.empty() && block.label != "entry") {
                indent_level = 0;
                output << block.label << ":\n";
                indent_level = 1;
            }
            
            for (const auto& instr : block.instructions) {
                emitInstruction(instr);
            }
        }
    }
    
    indent_level = 0;
    output << "    return 0;\n";
    output << "}\n";
    
    return output.str();
}

} // namespace caesar
