/**
 * @file codegen.cpp
 * @brief Caesar Code Generator implementation
 * @author J.J.G. Pleunes
 * @version 1.5.1
 */

#include "caesar/codegen.h"
#include <iomanip>

namespace caesar {

// ============================================================================
// Bytecode Generator
// ============================================================================

void BytecodeGenerator::emitByte(uint8_t byte) {
    output << std::hex << std::setw(2) << std::setfill('0') << (int)byte << " ";
}

void BytecodeGenerator::emitOpcode(const std::string& opcode) {
    output << opcode << " ";
}

void BytecodeGenerator::emitOperand(const IROperand& operand) {
    output << operand.toString() << " ";
}

std::string BytecodeGenerator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    output << "; Caesar Bytecode\n";
    output << "; Generated by Caesar Compiler v1.5.1\n\n";
    
    for (const auto& block : blocks) {
        if (!block.label.empty()) {
            output << block.label << ":\n";
            label_positions[block.label] = stack_size;
        }
        
        for (const auto& instr : block.instructions) {
            output << "  " << opcodeToString(instr.opcode);
            
            if (instr.dest.type != IROperandType::NONE) {
                output << " " << instr.dest.toString();
            }
            if (instr.src1.type != IROperandType::NONE) {
                output << ", " << instr.src1.toString();
            }
            if (instr.src2.type != IROperandType::NONE) {
                output << ", " << instr.src2.toString();
            }
            
            output << "\n";
        }
    }
    
    return output.str();
}

// ============================================================================
// x86-64 Assembly Generator
// ============================================================================

void X86_64Generator::emitPrologue() {
    output << "    ; Function prologue\n";
    output << "    push rbp\n";
    output << "    mov rbp, rsp\n";
    output << "    sub rsp, 64      ; Allocate stack space\n\n";
}

void X86_64Generator::emitEpilogue() {
    output << "\n    ; Function epilogue\n";
    output << "    mov rsp, rbp\n";
    output << "    pop rbp\n";
    output << "    ret\n";
}

std::string X86_64Generator::allocateRegister(const std::string& virtual_reg) {
    // Simple register allocation - map virtual registers to x86-64 registers
    static const std::vector<std::string> physical_regs = {
        "rax", "rbx", "rcx", "rdx", "rsi", "rdi", "r8", "r9", "r10", "r11"
    };
    
    auto it = register_map.find(virtual_reg);
    if (it != register_map.end()) {
        return it->second;
    }
    
    // Allocate new register
    int reg_idx = register_map.size() % physical_regs.size();
    std::string physical = physical_regs[reg_idx];
    register_map[virtual_reg] = physical;
    return physical;
}

void X86_64Generator::emitInstruction(const IRInstruction& instr) {
    std::string dest_reg = instr.dest.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.dest.value) : "";
    std::string src1_reg = instr.src1.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.src1.value) : "";
    std::string src2_reg = instr.src2.type == IROperandType::REGISTER ? 
                           allocateRegister(instr.src2.value) : "";
    
    switch (instr.opcode) {
        case IROpcode::LOAD_CONST:
            if (instr.src1.type == IROperandType::CONSTANT) {
                output << "    mov " << dest_reg << ", " << instr.src1.value << "\n";
            }
            break;
            
        case IROpcode::ADD:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    add " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::SUB:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    sub " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::MUL:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    imul " << dest_reg << ", " << src2_reg << "\n";
            break;
            
        case IROpcode::DIV:
            output << "    mov rax, " << src1_reg << "\n";
            output << "    cqo\n";
            output << "    idiv " << src2_reg << "\n";
            output << "    mov " << dest_reg << ", rax\n";
            break;
            
        case IROpcode::NEG:
            output << "    mov " << dest_reg << ", " << src1_reg << "\n";
            output << "    neg " << dest_reg << "\n";
            break;
            
        case IROpcode::EQ:
            output << "    cmp " << src1_reg << ", " << src2_reg << "\n";
            output << "    sete al\n";
            output << "    movzx " << dest_reg << ", al\n";
            break;
            
        case IROpcode::LT:
            output << "    cmp " << src1_reg << ", " << src2_reg << "\n";
            output << "    setl al\n";
            output << "    movzx " << dest_reg << ", al\n";
            break;
            
        case IROpcode::JUMP:
            output << "    jmp " << instr.dest.value << "\n";
            break;
            
        case IROpcode::JUMP_IF_FALSE:
            output << "    test " << src1_reg << ", " << src1_reg << "\n";
            output << "    jz " << instr.dest.value << "\n";
            break;
            
        case IROpcode::RETURN:
            if (instr.dest.type == IROperandType::REGISTER) {
                output << "    mov rax, " << dest_reg << "\n";
            }
            emitEpilogue();
            break;
            
        default:
            output << "    ; " << opcodeToString(instr.opcode) << " (not implemented)\n";
    }
}

std::string X86_64Generator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    register_map.clear();
    
    output << "; Caesar x86-64 Assembly\n";
    output << "; Generated by Caesar Compiler v1.5.1\n\n";
    output << "section .text\n";
    output << "global _start\n\n";
    output << "_start:\n";
    
    emitPrologue();
    
    for (const auto& block : blocks) {
        if (!block.label.empty() && block.label != "entry") {
            output << "\n" << block.label << ":\n";
        }
        
        for (const auto& instr : block.instructions) {
            emitInstruction(instr);
        }
    }
    
    output << "\n    ; Exit program\n";
    output << "    mov rax, 60      ; sys_exit\n";
    output << "    xor rdi, rdi     ; exit code 0\n";
    output << "    syscall\n";
    
    return output.str();
}

// ============================================================================
// C Code Generator (Transpiler)
// ============================================================================

std::string CCodeGenerator::indent() const {
    return std::string(indent_level * 4, ' ');
}

void CCodeGenerator::emitLine(const std::string& line) {
    output << indent() << line << "\n";
}

void CCodeGenerator::emitInstruction(const IRInstruction& instr) {
    switch (instr.opcode) {
        case IROpcode::LOAD_CONST:
            // Check if it's a string literal (starts with ")
            if (!instr.src1.value.empty() && instr.src1.value[0] == '"') {
                emitLine("const char* " + instr.dest.value + " = " + instr.src1.value + ";");
                register_types[instr.dest.value] = "const char*";
            } else {
                emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + ";");
                register_types[instr.dest.value] = "int64_t";
            }
            break;
            
        case IROpcode::GET_VAR: {
            // Get type from variable if known
            auto vit = variable_types.find(instr.src1.value);
            std::string var_type = (vit != variable_types.end()) ? vit->second : "int64_t";
            emitLine(var_type + " " + instr.dest.value + " = " + instr.src1.value + ";");
            register_types[instr.dest.value] = var_type;
            break;
        }
            
        case IROpcode::SET_VAR: {
            emitLine(instr.dest.value + " = " + instr.src1.value + ";");
            // Track variable type from source register
            auto it = register_types.find(instr.src1.value);
            if (it != register_types.end()) {
                variable_types[instr.dest.value] = it->second;
            }
            break;
        }
            
        case IROpcode::ADD:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " + " + instr.src2.value + ";");
            break;
            
        case IROpcode::SUB:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " - " + instr.src2.value + ";");
            break;
            
        case IROpcode::MUL:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " * " + instr.src2.value + ";");
            break;
            
        case IROpcode::DIV:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " / " + instr.src2.value + ";");
            break;
            
        case IROpcode::MOD:
            emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + " % " + instr.src2.value + ";");
            break;
            
        case IROpcode::NEG:
            emitLine("int64_t " + instr.dest.value + " = -" + instr.src1.value + ";");
            break;
            
        case IROpcode::EQ:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " == " + instr.src2.value + ";");
            break;
            
        case IROpcode::LT:
            emitLine("bool " + instr.dest.value + " = " + instr.src1.value + " < " + instr.src2.value + ";");
            break;
            
        case IROpcode::JUMP:
            emitLine("goto " + instr.dest.value + ";");
            break;
            
        case IROpcode::JUMP_IF_FALSE:
            emitLine("if (!" + instr.src1.value + ") goto " + instr.dest.value + ";");
            break;
            
        case IROpcode::RETURN:
            if (instr.dest.type != IROperandType::NONE) {
                emitLine("return " + instr.dest.value + ";");
            } else {
                emitLine("return 0;");
            }
            break;
            
        case IROpcode::PARAM:
            // Store parameter for next CALL
            call_params.push_back(instr.dest.value);
            break;
            
        case IROpcode::CALL: {
            // Handle built-in functions
            if (instr.src1.value == "print") {
                if (!call_params.empty()) {
                    std::string param = call_params[0];
                    // Check register type
                    auto it = register_types.find(param);
                    if (it != register_types.end() && (it->second == "char*" || it->second == "const char*")) {
                        emitLine("caesar_print_str(" + param + ");");
                    } else {
                        emitLine("caesar_print_int(" + param + ");");
                    }
                }
            } else {
                // User-defined function call
                std::string args;
                for (size_t i = 0; i < call_params.size(); i++) {
                    if (i > 0) args += ", ";
                    args += call_params[i];
                }
                emitLine("int64_t " + instr.dest.value + " = " + instr.src1.value + "(" + args + ");");
            }
            call_params.clear();  // Clear params after call
            break;
        }
            
        case IROpcode::PRINT:
            emitLine("printf(\"%lld\\n\", (long long)" + instr.dest.value + ");");
            break;
            
        default:
            emitLine("// " + opcodeToString(instr.opcode) + " (not implemented)");
    }
}

std::string CCodeGenerator::generate(const std::vector<BasicBlock>& blocks) {
    output.str("");
    variable_types.clear();
    register_types.clear();
    
    // First pass: collect all variables and track types
    std::unordered_map<std::string, std::string> temp_register_types;
    for (const auto& block : blocks) {
        for (const auto& instr : block.instructions) {
            // Track register types from LOAD_CONST
            if (instr.opcode == IROpcode::LOAD_CONST && instr.dest.type == IROperandType::REGISTER) {
                if (!instr.src1.value.empty() && instr.src1.value[0] == '"') {
                    temp_register_types[instr.dest.value] = "const char*";
                } else {
                    temp_register_types[instr.dest.value] = "int64_t";
                }
            }
            // Track variable types from SET_VAR
            if (instr.opcode == IROpcode::SET_VAR && instr.dest.type == IROperandType::VARIABLE) {
                auto it = temp_register_types.find(instr.src1.value);
                if (it != temp_register_types.end()) {
                    variable_types[instr.dest.value] = it->second;
                } else {
                    variable_types[instr.dest.value] = "int64_t";  // Default
                }
            }
            if (instr.opcode == IROpcode::GET_VAR && instr.src1.type == IROperandType::VARIABLE) {
                if (variable_types.find(instr.src1.value) == variable_types.end()) {
                    variable_types[instr.src1.value] = "int64_t";  // Default
                }
            }
        }
    }
    
    output << "// Caesar C Code\n";
    output << "// Generated by Caesar Compiler v1.5.1\n\n";
    output << "#include <stdio.h>\n";
    output << "#include <stdint.h>\n";
    output << "#include <stdbool.h>\n";
    output << "#include <string.h>\n\n";
    
    // Caesar built-in functions
    output << "// Caesar built-in functions\n";
    output << "void caesar_print_int(int64_t val) { printf(\"%lld\\n\", (long long)val); }\n";
    output << "void caesar_print_str(const char* val) { printf(\"%s\\n\", val); }\n\n";
    
    output << "int main() {\n";
    
    indent_level = 1;
    
    // Declare all user variables at the top
    if (!variable_types.empty()) {
        emitLine("// User variables");
        for (const auto& var : variable_types) {
            emitLine(var.second + " " + var.first + " = 0;");
        }
        output << "\n";
    }
    
    for (const auto& block : blocks) {
        if (!block.label.empty() && block.label != "entry") {
            indent_level = 0;
            output << block.label << ":\n";
            indent_level = 1;
        }
        
        for (const auto& instr : block.instructions) {
            emitInstruction(instr);
        }
    }
    
    indent_level = 1;
    emitLine("return 0;");
    indent_level = 0;
    output << "}\n";
    
    return output.str();
}

} // namespace caesar
